openaps/oref0

- bin/oref0-get-profile.js
- lib/profile/index.js
get-profile collects carb_ratio, but we don't use that anywhere else in oref0, so before people get all their aliases set up, we should remove it.
> remove carb_ratio

- README.md
- bin/oref0-calculate-iob.js
- lib/iob/history.js
The only difference in `calculate-iob` and this version was that I added sorting to the data before `calcTempTreatments` was run, instead of after.  It turns out it's important to not change the ordering before `calcTempTreatments` figures things out.
> fix error introduced in divide and conqeuor

- bin/ns.sh
Use the NS API regex support to filter treatments on the server, fixes a bug where 5 or more non-openaps treatments get added after an openaps treatement
> filter treatments on the server instead of on the client

- tests/iob.test.js
will delete my branch after this
> a little iob test clean up

- bin/mm-format-oref0-glucose.sh
- bin/ns-dedupe-treatments.sh
- bin/ns-uploader-setup.sh
- bin/oref0-calculate-iob.js
- bin/oref0-determine-basal.js
- bin/pebble.sh
- bin/pumpsettings.sh
- lib/iob/calculate.js
- lib/iob/history.js
- lib/iob/total.js
- tests/determine-basal.test.js
- tests/iob.test.js
* Add tool with @tghoward, to format mm style glucose records to what the oref0
tools expect.
> dev branch - prepping next release

- lib/determine-basal/determine-basal.js
Check for both min and max exist. Typo was just checking max twice.
> Fix typo for profile.min_bg

- bin/ns-uploader-setup.sh
If the `monitor/glucose.json` file happens to be deleted the `cp` would fail until `openaps get-bg` is run manually, by adding the touch a file will be created if it doesn't already exist.
> touch monitor/glucose.json before trying to cp it

- tests/determine-basal.test.js
eventualBG < min_bg with delta > exp. delta
Reflects situation I encountered where no low temp was given despite eventualBG being well below min_bg because bg was not falling as fast as expected
> Add additional 'should low-temp' test

- lib/determine-basal/determine-basal.js
- tests/determine-basal.test.js
This creates a unit test for #48, the issue @audiefile and @jasoncalabrese identified where expected-delta wouldn't low-temp when eventualBG < min but delta > expected delta (BG is falling more slowly than expected delta, mostly due to BGI).  Previously, I believe we were comparing delta to BGI/2, but in the expected-delta branch I changed it to compare to expected_delta (basically BGI), and haven't yet applied the newinsulinReq adjustment logic that I did for reducing high-temps.
This basic fix will disable the expected delta comparison completely (and low-temp) any time you’re falling with eventualBG < min.  That fixes the new unit test and doesn’t break any others, but I think the quick-fix will be too aggressive at low-temping when carbs are causing you to fall a lot slower than BGI, …
> test capturing @audiefile scenario and overcompensatory quick-fix

- bin/mm-format-ns-profile.sh
It seems there were some typos, positional variables were overlapping each other. Also I have put a default output file name.
> Corrected positional arguments for NS profile creation

- bin/ns-status.js
- bin/oref0-raw.js
- lib/require-utils.js
- lib/with-raw-glucose.js
- tests/with-raw-glucose.test.js
I want to be able to use raw bg in some times, but also want to be safe about it.  In this first pass theres a `maxRaw` that defaults to 150.  The tool will always add a `raw` field, but will only set `glucose` to `raw` when `glucose` is missing or `< 40` and `raw < maxRaw` to prevent a lot high temping from raw.
Might be good to add some limits around the delta to ignore big swings.
This should be helpful with the wixel too.
> a tool to support filling in raw glucose values

- lib/profile/targets.js
Change from 100 to 90 as it is meant to be a minimum bound in case of user entry error. In this case a user (me) is trying to set it to 90 on purpose which is a reasonable value.
> Lower max override from 100 to 90

- lib/profile/carbs.js
I added a check for the carbratio.data == "exchanges" because this is the alternative setting to the unit "grams". If "exchanges" is used in the pump the information behind the ratio is how many insulin units are needed for 1 bread exchange unit (= 12 grams of carbohydrate). To make this entered value fitting in the Openaps system, which uses "grams" as an value that says how many grams are matching 1 unit of insulin, the carbRatio.ratio is recalculated to grams per unit in the case the pump value is based on insulin per bread exchange unit. For some users (like me) it could be better to adjust the recalculating factor from 12 to 10. This is the case if the German "Kohlenhydrateinheit" (= 10 grams of carbohydrate) is used instead of the classic bread exchange unit (= 12 grams of …
> Now carbs.js is able to handle the pump setting "exchanges" as well

- bin/oref0-detect-sensitivity.js
This should fix #117.
edison@edison-rl ~/openaps-dev $ openaps report invoke settings/autosens.json
detect-sensitivity://text/shell/settings/autosens.json
Optional feature autosens disabled: not enough glucose data to calculate sensitivity
reporting settings/autosens.json
edison@edison-rl ~/openaps-dev $ cat settings/autosens.json
{ "ratio": 1, "reason": "not enough glucose data to calculate autosens" }
> Generate a warning, not a fatal error, on insufficient glucose data for autosens

- bin/nightscout.sh
- bin/oref0.sh
Eg: `oref0 cron-5-minute-helper openaps do-everything`
```bash
$ oref0 cron-5-minute-helper openaps do-everything
SHELL=/bin/bash
PATH=/home/bewest/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/home/bewest/.cabal/bin:/home/bewest/.cabal/bin
*/5 * * * * (cd /home/bewest/Documents/foobar && time openaps do-everything) 2>&1 | logger -t openaps-loop
```
```bash
$ oref0 cron-5-minute-helper
SHELL=/bin/bash
PATH=/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games
*/5 * * * * (cd /home/edison/openaps && time openaps do-everything ) 2>&1 | logger -t openaps-loop
```
Can be used by piping into `crontab -`:
```bash
edison@ubilinux:~/openaps$ oref0 cron-5-minute-helper | crontab -
edison@ubilinux:~/openaps$ 
edison@ubilinux:~/openaps$ …
```
> create a cron-helper tool

- lib/meal/total.js
Since we get carbs from multiple sources, use the parsed date in logging instead of the raw `treatment.timestamp`
> clean up meal date logging

- bin/oref0-reset-git.sh
Tested by inserting a 30 second sleep at the start of fix-git-corruption, which gets killed after 15 seconds as expected.
> Don't wait for 15 seconds if the oref0-fix-git-corruption completed

- bin/oref0-determine-basal.js
- lib/determine-basal/determine-basal.js
- lib/profile/index.js
- tests/determine-basal.test.js
- Round to doses the pump can provide - accurate for x23 and x54. For doses < 1u it will produce values between ones x22 pumps can provide, but this shouldn't be any worse than the current behaviour.
- As a result of rounding basal doses better, it should be possible to replace most of the checks that ballpark within 0.1u/hr.
- Convert some of the output numbers to mmol/l. This is mostly where actual blood glucose values are displayed, not delta or BGI values (because of the loss of resolution when rounding)
- Add tests for basal rounding
- get-profile now includes the pumps preferred unit setting
- Alter the require structure to allow access to round_basal outside of the .js file for tests.
> Various determine-basal changes

- lib/determine-basal/determine-basal.js
In some cases, due to floating point error, this was outputting strings like 2.00000000000001. Rounding should prevent that.
> Round basaliob, was outputting very long floats

- bin/oref0-determine-basal.js
- bin/oref0-get-profile.js
- lib/basal-set-temp.js
- lib/determine-basal/determine-basal.js
- lib/profile/index.js
- lib/round-basal.js
- tests/determine-basal.test.js
Previous attempts at rounding basal were thwarted by another set of rounding in SetTempBasal. Pull the round basal function out in to a separate file to make it easier to call in multiple places.
Add model.json to the profile produced by get-profile. This model is now used by round_basal to choose an appropriate precision for doses in the sub-1u region. 
Undo previous changes to how determine-basal is require()'d by other files - they are no longer needed with round_basal in another file.
> Round basal

- lib/round-basal.js
Saw a report of determine-basal crashing because `typeof profile.model` was `Object` - profile.json contained `'model':{}`. Moved to a stricter check.
> Better check for whether model is present

- bin/nightscout.sh
I run openaps with all output being appended to a log file. I was getting repeated truncation of the logfile whenever nightscout.sh was writing to /dev/stderr. Changing to >&2 seems to fix the problem, and should be more portable.
> Change > /dev/stderr to >&2 for portability and weird file truncation

- bin/ns-status.js
Puts a battery percentage in the upbat pill of Nightscout. Expects a file that contains a single number, the battery percentage.
uploader.json could be generated with the following `root` cronjob (`sudo crontab -e`)
`*/5 * * * /path/to/EdisonVoltage/voltage 3 > /path/to/openaps/uploader.json`
I've tested the various combinations of --uploader uploader.json / mmtune.json and they all seem to work.
> Uploader battery status

- bin/mm-format-ns-glucose.sh
- lib/determine-basal/determine-basal.js
Output formatting for determine-basal changed in ama, converting the new format to mmol/l
mm-format-ns-glucose was taking a *long* time on my PI. Switching to `json -E` fixed that
```
Compatibility  note:  There is also a -e CODE option (lowercase "e") from earlier versions of json to do much the same thing (with slightly different semantics for the CODE). It is still supported for backward compatibility.
However it is deprecated because it can cause processing to be 10x or more slower for large inputs. See the COMPATIBILITY section below.
```
> JSON speedup, BG conversions

- lib/determine-basal/determine-basal.js
Outputting the wrong target value when eventualBG > target.
> Print max_bg, not profile.max_bg

- bin/oref0-determine-basal.js
- lib/glucose-get-last.js
NS wasn't giving a reason for loop not running and it turned out to be the "BG data out of date" case that was causing it. This change allows the error message to be passed to Nightscout.
> Pass the "BG data out of date" message on to nightscout

- lib/basal-set-temp.js
- tests/set-temp-basal.test.js
Fix rounding error that was preventing small changes to small basal rates. Use round_basal instead. #164
> Fix rounding error for small basal rates.

- lib/determine-basal/determine-basal.js
- tests/determine-basal.test.js
Fix another rounding error involving small basals. 
This would lead determine-basal to suggest a rate higher than maxSafeBasal by as much as 2x (e.g. .05 -> .1). Fortunately, setTempBasal enforces the maxSafeBasal constraint a second time, and there the rounding is done correctly. So the only impact was that the values shown in the reason were wrong. #164
> Fix rounding error when lowering rate to maxSafeBasal.

- lib/determine-basal/determine-basal.js
- lib/glucose-get-last.js
- tests/determine-basal.test.js
Per discussion in https://github.com/openaps/oref0/issues/164, it looks like it'd be better to smooth out our reaction to CGM variation by making many of our decisions on the 10m delta instead of the 5m delta.
> Use 10m instead of 5m lookback for deviation

- lib/glucose-get-last.js
This needs to be tested with non-MDT cgm. MDT CGM output has the date in a different format, this will choose `date` if it is present, otherwise it will look for `display_time`.
> Support display_time in getLastGlucose

- bin/oref0-get-profile.js
- lib/determine-basal/cob-autosens.js
- lib/determine-basal/determine-basal.js
- lib/glucose-get-last.js
- tests/determine-basal.test.js
- tests/get-last-glucose.test.js
calculate and use new short_avgdelta (using avg of deltas from all data points 5-15m ago) and long_avgdelta (using avg of deltas from all data points 20-40m ago) vs. "now" (avg of all data points within last 2.5m)
This should mean we can have multiple rigs uploading BGs from multiple receivers and it won't affect our deltas.  It should also mean that our deltas are less jumpy, as we'll be using the average of several deltas in each case rather than just picking one arbitrarily.
Before merge, need to actually test this in production to verify we get expected behavior with a single rig, and then add uploads from a second receiver and verify everything stays happy.
> support multiple receivers, and use all recent data points for avgdeltas

- lib/determine-basal/determine-basal.js
If the numeral after the decimal point is zero it is dropped when concatenated in the 'reason' field, leading to nightscout feedback like "Eventual BG 0.2 < 6". This commit restores the decimal point. Also changed in mg/dl case for consistency, although this should have no effect.
> Always display bg in mmol/L to one decimal point

- lib/determine-basal/cob-autosens.js
- lib/determine-basal/determine-basal.js
- lib/profile/carbs.js
- lib/profile/index.js
- package.json
- tests/profile.test.js
I'm using this so we can set higher than normal carb ratios on the pump, and cause the bolus wizard to calculate a partial bolus, but then correct the carb ratio used for AMA so we can catch up if/when there's a rise.
Might need to also adjust the min up CI from the current 3mg/dL/5m, but planning on experimenting without that first.
> add new carbratio_adjustmentratio preference

- bin/nightscout.sh
$ `openaps use ns shell oref0_glucose_since -10hours | jq '. | length'`
123
$ `openaps use ns shell oref0_glucose_since -5hours | jq '. | length'`
60
$ `openaps use ns shell oref0_glucose_since -30minutes | jq '. | length'`
6
$ `openaps report add monitor/glucose-ns-recent.json JSON ns shell oref0_glucose_since -6hours tz`
> A new Nightscout helper to get glucose since some time ago

- bin/oref0-setup.sh
When running the setup script, entering a valid $NIGHTSCOUT_HOST resulted in
"Ok, no Nightscout for you"
being printed if no TTY port was specified for mmeowlink
> Fixed wrong test for $NIGHTSCOUT_HOST echo

- lib/oref0-setup/report.json
This should fix the warning from running the `monitor/meal.json` report.
> Match input reports to meal.json with their correct categories (basal, glucose, carbs). 

- bin/oref0-setup.sh
- lib/oref0-setup/alias.json
- lib/templates/refresh-loops.json
can just use cp -pu instead of the rsync command. Using cp makes it more
portable since it's part of the core tools, whereas rsync may require an additional install in some
distros.
> Simplify Copy of Newer Files / Script Cleanup

- bin/clockset.sh
- bin/oref0-setup.sh
- headless/headless.sh
- lib/oref0-setup/alias.json
- lib/oref0-setup/mdt-cgm.json
- lib/templates/refresh-loops.json
**Rationale**
Backtick command substitution \`..\` is legacy syntax with several issues.
- It has a series of undefined behaviors related to quoting in POSIX.
- It imposes a custom escaping mode with surprising results.
- It's exceptionally hard to nest.
$(..) command substitution has none of these problems, and is therefore strongly encouraged.
> Backtick replacement

- bin/oref0-setup.sh
The script was using the integer comparison operator -ne which gives a syntax error if the operand has a decimal point. Use string comparison instead.
> Support floating point max-iob in setup. 

- bin/oref0-setup.sh
For Jubilinux, this line needs to be added to /etc/rc.local
bluetooth_rfkill_event >/dev/null 2>&1 &
It looks like you handle this in the install scripts by running those commands on startup. So I've added that line to that section. Hope I got that right.   I'll also add it to other instructions (already added to TC2013 script).
> add bluetooth line to make it work with Jubi

- lib/oref0-setup/report.json
Among other things, this is needed so that small basal rates are rounded appropriately.
> Setup should include the model in profile.json. 

- bin/oref0-reset-git.sh
- bin/oref0-setup.sh
- bin/oref0-truncate-git-history.sh
- package.json
This should prevent the .git directory from growing uncontrollably.  If garbage collection fails and it does grow to fill the disk, it should now go ahead and rm -rf .git and re-init.
> truncate git history at 2000 commits

- bin/oref0-setup.sh
Turns out `npm view` shows what's in npm, not installed locally. We actually want `npm list`
Thanks @dougtakeuti @Bender1061 @logichammer @C-Ville for helping me find and fix this.
> fix oref0 version check in oref0-setup

- lib/determine-basal/cob-autosens.js
- lib/determine-basal/determine-basal.js
- lib/glucose-get-last.js
- lib/oref0-setup/alias.json
- lib/templates/refresh-loops.json
While Dexcom uses values at 30 and below as error states, xDrip uses the values at 31 to 38 as additional error states (only 38 used/propagated) so far.
Those values are not used by Dexcom as they map LOW to 39 and the normal range it shows values starts with 40.
NightScout shows it as error "38?? ✖︎".
I don't use Oref0 but AndroidAPS, but I hope I have found all cutoffs. I've looked at all ocurrences of "30" in the sourcecode and checked if it was a cutoff or not.
> Handle xDrip errorstate 38

- lib/oref0-setup/alias.json
- lib/oref0-setup/mdt-cgm.json
- lib/templates/refresh-loops.json
This change removes pump history upload to the Nightscout entries collection.
Reasons for the change:
1. Pump history is already uploaded to treatments. It belongs in that collection and not in entries.
2. It causes problems when backfilling sgv to the entries collection. The `recent-missing-entries` algorithm does not distinguish between sensor and pump history data in the entries collection. This causes the algorithm to think there are no sgv gaps if there is history data around the same time, event though those items are being uploaded independently of each other. This causes valid sgv entries to be removed from the NS upload incorrectly, resulting in gaps.
Relevant PRs:
https://github.com/openaps/decocare/pull/16
https://github.com/openaps/oref0/pull/287
> Remove treatment data upload to NS entries

- lib/oref0-setup/mdt-cgm.json
oref0-setup provides a mechanism to fetch NS cgm in addition to device cgm so that the newer of the two can be used in the loop. This change removes that Nightscout entries fetch when using `MDT` cgm.
Reasons for the change:
1. NS fetch is unnecessary with MDT cgm. There is a very low likelihood that NS will have newer sgvs than the pump device when using `MDT` as the cgm source for oref0. 
2. Reliability of NS entries upload. The NS fetch has been observed to cause a problem with the `recent-missing-entries` report which causes duplicate entries and inconsistency in the NS uploaded entries.
Related PRs:
https://github.com/openaps/oref0/pull/288
https://github.com/openaps/decocare/pull/16
> Remove get-ns-bg from ns-loop for MDT cgm

- bin/oref0-dexusb-cgm-loop.py
- bin/oref0-setup.sh
- package.json
most important one to add 'python -u' for unbuffered output. otherwise
the logging will not be added when started from crontab for some reason
> improvements to dexusb

- bin/oref0-online.sh
- bin/oref0-setup.sh
To pair with phone
reboot edison
```
sudo killall bluetoothd; sudo /usr/local/bin/bluetoothd --experimental &
sudo hciconfig hci0 name $HOSTNAME
bluetoothctl
power off
power on
discoverable on
agent on
default-agent
```
**************************
for android
select device from phone
Type **yes** on terminal
**************************
for iPhone
```
pair AA:BB:CC:DD:EE:FF
```
Type **yes** on terminal
**************************
type 
```
trust AA:BB:CC:DD:EE:FF
```
> Bt device name

- bin/mm-format-ns-glucose.sh
- bin/mm-format-oref0-glucose.sh
- bin/nightscout.sh
This change causes the oref0 and nightscout scripts to treat GlucoseSensorDataLow (<40) and GlucoseSensorDataHigh (>400) events as type=sgv events. As before, oref0 continues to treat regular GlucoseSensorData events as type=sgv.
There is a relevant PR in decocare that adds the decoding of the newly discovered high and low events: https://github.com/openaps/decocare/pull/16.
> Process high and low events as type sgv

- bin/oref0-reset-git.sh
This detects and fixes an additional type of git corruption due to a broken HEAD reference.
All openaps report commands were failing with the following callstack:
```
Traceback (most recent call last):
File "/usr/local/bin/openaps-report", line 8, in <module>
execfile(__file__)
File "/home/pi/src/openaps/bin/openaps-report", line 82, in <module>
app( )
File "/home/pi/src/openaps/openaps/cli/__init__.py", line 52, in __call__
self.epilog( )
File "/home/pi/src/openaps/bin/openaps-report", line 69, in epilog
super(ReportToolApp, self).epilog( )
File "/home/pi/src/openaps/openaps/cli/__init__.py", line 75, in epilog
self.create_git_commit( )
File "/home/pi/src/openaps/openaps/cli/__init__.py", line 98, in create_git_commit
self.repo.index.commit(msg)
File …
```
> Detect and fix additional case of git corruption (broken HEAD).

- bin/oref0-bluetoothup.sh
- bin/oref0-online.sh
- bin/oref0-setup.sh
- bin/peb-urchin-status.sh
- lib/oref0-setup/pancreabble.json
- lib/oref0-setup/pancreoptions.json
- package.json
add on @mddub 's Pancreabble to the oref0-setup.
the peb-urchin-status.sh is not by any means perfect. but it does work. Easy to turn on and off the different types of statues you would like by changing the bools in pancreoptions.json
Ideas on what statues and notifacations to to add to this would be most helpful.
Almost need a way to know if a value has already been sent to the watch, to prevent duplicate notifications. This would also be an easy way to warn you that your battery is low. But I was unable to make the script write to a json file.
follow https://github.com/mddub/pancreabble for instructions on Pairing Pebble to rig.
I have not tested with a Pi.
Added the oref0-bluetoothup to simplify turning on the bluetooth when BlueZ is installed.
Pebble Mac address can be sound in …
> Pancre add

- tests/iob.test.js
Lack of current_basal causes these tests to error with latest changes to dev due to required values being `undefined`. Hopefully these values are appropriate.
> Add current_basal and basalprofile to two failing tests

- bin/oref0-mdt-trend.js
- package.json
As the title says, attempt to replicate Dexcom trend arrows from Medtronic data. The new command is intended to run on "raw" glucose data from the pump (`iter_glucose` output). 
I ran it locally as `./oref0-mdt-trend.js monitor/glucose_raw.json > monitor/glucose.json; `.
`monitor/glucose.json` can then be used as normal.
The script calculates the rate of change in blood sugar for all BG data in the last 15 minutes, then computes an average of those. An average change of < 1mg/dl/min is "flat", 1-2 is 45 degrees, 2-3 is single arrow, 3+ is double arrow.
Testing would be welcome.
> Add trend arrows to medtronic glucose data

- bin/mm-format-ns-treatments.sh
Currently, MDT sensor alarms just show "SensorAlarm <pumpmodel>" in the notes field on nightscout. This change should use the "alarm_description" field for the note if present (e.g. "High Glucose" or "Cal Reminder").
Not yet ready for merge, needs more testing first (from me, if not from others).
> MDT sensor alarms: If we have an alarm description, use it.

- bin/oref0-autotune.sh
It will not search the path for the installed version.  The previous would not work on a non-openaps install
> Updated calling of oref0-autotune-prep

- bin/oref0-setup.sh
In addition to max_iob, allow the following from preferences.json to be specified during setup:
- max_daily_safety_multiplier
- current_basal_safety_multiplier
- bolussnooze_dia_divisor
- min_5m_carbimpact
> Allow additional preferences to be customized in oref0-setup

- lib/determine-basal/determine-basal.js
@scottleibrand, @MilosKozak 
This is my proposition of how to handle running low temps. If `currenttemp.minutesrunning` is not defined (like in Oref0), it will be assumed that the overall length is 30 minutes.
This will reduce the changed calculation of `30-minutes_running` to `30-(30-currenttemp.duration)` = `currenttemp.duration` and not change anything for the default case.
In case the overall duration is longer (as in some cases in AndroidAPS), it will be calculated as if it was 30 minutes long.
If a low temp is actually running longer than 30 mintues, `adjEventualBG` will rise over `eventualBG` and the "keep it running" branch will not be entered. (As the `eventualBG < min_bg` situation is already handled above.)
> lowtempimpact based on 30 minutes

- bin/oref0-bluetoothup.sh
- bin/oref0-online.sh
- bin/oref0-setup.sh
And if wifi is not working (for example an open wifi with a captive portal) but Bluetooth is, it will disable wifi (release the wlan0 IP) until Bluetooth goes away (most likely after you get home and kill the hotspot manually).  If it doesn't have to do that, it gracefully turns off Bluetooth when it gets a working wifi IP.
> Support multiple bluetooth MACs

- lib/iob/history.js
Needed to change the timestamp and rate to created_at and absolute respectively.
> Added additonal logic for HAPP Temp basals

- bin/oref0-mdt-trend.js
- lib/oref0-setup/mdt-cgm.json
Add medtronic trend data to the default oref0-setup script. Takes in `monitor/cgm-mm-glucosedirty.json`, produces `monitor/cgm-mm-glucosetrend.json`. 
`cgm/cgm-glucose.json` then reads `glucosetrend.json` instead of `glucosedirty.json`.
Also fixes an issue where the _tell resets halfway through glucose data (caused by sensor restart?)
> Mdt trend setup

- lib/oref0-setup/alias.json
Setting temporary targets from Nightscout doesn't work for anyone in timezones +0600 or greater and is probably patchy for anyone in +0100 to +0500. The alias `ns-temptargets` filters `treatments.json` by date string to keep only those in a 6 hour lookback (it also looks for the word "Targets" in the `eventType`.
However, the date used for comparison is in the user's timezone, and NS dates are UTC. This PR adds the flag `-u` to the unix `date` command to use UTC instead.
Should also be noted somewhere that any temporary targets greater than 6 hours in duration will be terminated at the 6 hour mark.
> fix ns-temptargets

- lib/meal/total.js
Improperly sorted treatments appear to be causing, or at least contributing to, https://github.com/openaps/oref0/issues/390, in cases where carbs come from multiple sources (in the Crawford's case, both pump and NS).  This PR makes sure they're sorted properly before calculating COB.
> Sort treatments before calculating COB

- bin/oref0-autotune.py
I decided to tackle the Python version of Autotune. This is a work-in-progress.
-  **Add ability to use API secret for Nightscout**. #397
There are three separate places in the code that make a call to the Nightscout server. Using Python's request module, this would fairly straightforward to implement the API secret during these calls.
- **Convert Nightscout profile to OpenAPS profile format.** #300
If a Nightscout profile to OpenAPS profile converter is created, it would be fairly simple to add that as an argument `--use-nightscout-profile` and *get_nightscout_profile()* could be called instead of *get_openaps_profile()*.
- **Support running on all platforms.** 
Using Python is a step closer to manual mode being run on all platforms without a VM.
- **Better input checking, …
> Autotune: Porting to Python - oref0-autotune.py

- bin/oref0-radio-reboot.sh
- bin/oref0-setup.sh
- package.json
Sometimes, particularly after oref0-online restarts networking and/or switches back and forth between Bluetooth and wifi lots of times, we'll see the issue described at https://github.com/openaps/oref0/issues/406#issuecomment-281543469 and will need to reboot to fix.  This PR attempts to safely automate rebooting only in that situation.
> spidev5.1 already in use reboot

- bin/oref0-delete-future-entries.sh
- bin/oref0-setup.sh
- package.json
This runs a bash Script when the system reboots that checks the Date on the last CGM entry in monitor/glucose to see if that is in the future of the current time.
This is only an issue with the network was not available and the clock was not automatically set.
If the date of the rig is still in 1999 and it sees that the time is in the future. 
all the other checks in the Loop only look to see if the time is older than current system time.
so if you have a monitor/clock-zoned.json that time will not always be current when the oref0-set-system-clock is run, it will either not set the clock correctly, or the time that is there is from when the rig was last ran.
so if the time is in the future of the rig, it will delete the contents of the monitor folder, allowing the rig to fully grab all …
> Delete Future Data for better recovery of Time on System during No network power on for edison

- bin/oref0-setup.sh
Fixes: Consistent use of $HOME isntead of ~
Fixes: Installs $HOME/src/subg_rfspy for ww pump users, if it's not
there. Otherwise WW-pumps won't work.
> cherrypicks of the devww branch for the next oref0-release.

- lib/autotune-prep/categorize.js
Need some testing to determine if this is a reasonable approach, and whether `iob.iob > currentBasal` is a good IOB threshold for triggering UAM detection, or if it should be higher (maybe `2 * currentBasal`?)
> add unannounced meal detection to autotune

- bin/oref0-autotune.sh
This patch will allow oref-autotune.sh to use the environment variable API_SECRET_READ.  This contains the unhashed API Secret needed to read from Nightscout when the default read permission is deny.
> Updated to use API_SECRET_READ for the api key needed to read from

- bin/oref0-setup.sh
Adding a new cronline for proper shutdown in case the edison battery is empty (< 3050mV; 2950mV is dead)
* running each 15 min (in case of failure one is able to power on and perform `crontab -r`
* using `openaps battery-status`
* parsing monitor/edison-battery.json using `awk` searching for the 2nd column `$2` for the voltage value
* e.g. content of monitor/edison-battery.json `{"batteryVoltage":4057, "battery":88}`
* in case the voltage is < 3050mV `sudo shutdown -h now` will be performed
* when monitor/edison-battery.json is empty or does not exist, nothing is done
> oref0-setup.sh new cron line for proper shutdown

- lib/determine-basal/determine-basal.js
- lib/meal/total.js
Currently AMA considers carbs up to 1.5*DIA hours old, but the pumphistory-zoned.json file only has 5 hours of insulin history.  As a result, when boluses age off at the 5h mark, carbs associated with them are decayed more slowly (often at min_5m_carbimpact), resulting in COB "coming back from the dead".  The longer-term solution to this is probably to merge the pumphistory-zoned.json with the pumphistory-24h-zoned.json so we can properly decay carbs back to 1.5*DIA, but until we do that, it would be safer to exclude carbs from more than DIA hours ago (typically 3-4h).
> only consider carbs from last DIA hours as a workaround for undead carbs

- bin/oref0-setup.sh
Now checks for at least version 5.37, and will install 5.44 if no new enough version found.
> Implement BlueZ min version checking.

- bin/oref0-pump-loop.sh
When the Edison battery level is below 60%, this makes the rig stop running autosens every 20m, and instead run it every 90m.  It also causes oref0-pump-loop to wait up to 5 minutes for a BG reading newer than the most recent temp basal reading before even trying to use the radio or talk to the pump.  In combination with a new subg_rfspy firmware that I'm testing with @mogar, this should allow us to power down the cc1110 radio most of the time when necessary.
For now, I'm leaving the low battery cutoff at 60%, as the charging voltage reads at about 62-65%.  After some testing, we might want to make this the default mode whenever the rig is not actually plugged in (when battery reads >65% as well as <60%).
> Save battery

- bin/oref0-detect-sensitivity.js
- lib/autotune-prep/categorize.js
- lib/determine-basal/cob-autosens.js
- lib/profile/index.js
Implements https://github.com/openaps/oref0/issues/447
This has been tested and confirmed to:
- Do nothing when the preference is not enabled
- Do nothing when the last site change was more than 24h ago
- Reset autosens to neutral after a site change:
```
Setting lastSiteChange to Fri Apr 28 2017 22:38:09 GMT-0700 (MST) using timestamp 2017-04-28T22:38:09-07:00
----++++++++++- Found 15 deviations since Fri Apr 28 2017 22:38:09 GMT-0700 (MST) - adding 11 more zero deviations
18% of non-meal deviations <= 0 (target 45%-50%)
Sensitivity normal.
```
> Reset autosens on site change

- bin/oref0-radio-reboot.sh
- bin/oref0-setup.sh
- bin/oref0_init_pump_comms.py
- bin/oref0_subg_ww_radio_parameters.py
This will reboot the rig if hanging rig-pump communication is detected.
This pull request also improves logging, has more robust killing of reset.py if it hangs.
The root cause of this issue is discussed here https://github.com/oskarpearson/mmeowlink/issues/60
> workaround for hanging rig-pump communication (with WW pump)

- bin/oref0-pump-loop.sh
This checks whether the get-bg alias is configured for a MDT CGM, and if so, skips the wait_for_bg (since we have to talk to the pump anyway to get BG data) and performs `openaps get-bg` as the MDT `openaps pump-loop` alias does, right after wait-for-silence.  Needs testing by @ericfeibelman and anyone else trying to run MDT CGM with SMB.
> Add MDT Enlite CGM support to oref0-pump-loop for SMB

- bin/oref0-online.sh
- bin/oref0-pump-loop.sh
- bin/oref0-pushover.sh
- bin/oref0-setup.sh
- lib/basal-set-temp.js
- lib/determine-basal/determine-basal.js
- lib/meal/total.js
- package.json
- tests/determine-basal.test.js
Most significant changes in this PR, in order of appearance in the diff:
- oref0-online updates for stability
- oref0-set-device-clocks if pump clock is >1m off
- oref0-set-system-clock if determine-basal complains it's set incorrectly
- support for oref1 pushover alerts of insulinReq and carbsReq
- allow non-SMB code paths to set temps up to 120 minutes when needed
- allow non-zero temps in SMB mode when lastCOBpredBG > target_bg
- don't SMB if basal is < 0.3 U/hr (if 0.1U SMB represents >20m of basal)
> Pushover support for carbsReq and insulinReq notifications

- lib/basal-set-temp.js
- lib/determine-basal/determine-basal.js
One of the changes merged to dev from the pushover branch attempted to disable low glucose suspend mode when IOB was highly negative, but that change went too far and mostly disabled LGS.  This fixes LGS to only be disabled when IOB is already super negative and BG is rising faster than predicted (such as from a meal eaten after a long period of zero temping).  It also adds that information to the reason field when disabling LGS.
> Fix low glucose suspend

- bin/oref0-determine-basal.js
- bin/oref0-setup.sh
Per https://github.com/openaps/oref0/issues/468, this is a proposed solution to check for the presence of autotune directory folder, to further the strong recommendation that people only use oref1 features with well-tuned basals. This folder is created when someone’s enabled autotune to run nightly; or by running autotune manually.  
To test, grab the autotune-check branch.
You may want to uncomment line 110 (("Printing this so you know it's getting to the check for autotune.") to help you spot the output in the logs.
If you have autotune enabled already and running (and an existing directory), you should see the “Autotune exists! Hoorah!” message in your logs, along with a note about microbolus being set to true. 
To test this works properly, you then want to change the name of your …
> Adding a check for existing autotune folder. If it does not exist, warn user that microbolus-related features will be disabled.

- bin/oref0-determine-basal.js
- lib/determine-basal/determine-basal.js
The current pushover alerts tend to false-alarm for carbsReq when BG is still high and there's plenty of time to prevent a low with SMB zero temps.  Rather than simply including 30m worth of zero temps in calculating carbsReq, this calculates how many minutes BG is expected to stay above min_bg (the low end of your target range) and includes that many minutes worth of zero temp in the carbsReq calculations.  So if you aren't projected to go low for 90 minutes, it'll include 90m worth of zero temps, and likely won't alarm prematurely for carbsReq.  If you're already below target, or projected to drop below target in just a few minutes, it'll be much more apt to pushover for carbsReq.
> Smarter carbsReq

- bin/oref0-setup.sh
- package.json
For release 0.4.2 a github checkout of the master branch was used. Therefore a change in mraa could break openaps. For the master branch we
should always use a mraa release instead of a master branch checkout.
This fixes https://github.com/openaps/oref0/issues/500 and makes it possible again to install openaps.
Rigs that have already mraa installed were not affected with this issue and there is no immediate need to upgrade from 0.4.2 to 0.4.3.
> Hotfix for mraa

- bin/oref0-setup.sh
Needed for testing MRAA fix to see if their master branch works again with OpenAPS
Todo: decide which version we will use on OpenAPS dev and for the 0.5.0 release.
> Use MRAA master on oref0 dev branch again

- bin/oref0-pump-loop.sh
- lib/profile/index.js
Per https://github.com/openaps/oref0/issues/175, sometimes people forget to resume / unsuspend their pump after reconnecting it.  This would cause oref1 to automatically resume the pump if the underlying zero temp has expired.  As long as the zero temp is still running, it would honor the suspend status and do nothing.  As written, this would not apply to users running the old `openaps pump-loop`, only people who have enabled microboluses in oref0-setup and are using oref0-pump-loop.sh.
Thoughts?
> unsuspend pump automatically if temp basal duration is zero

- bin/oref0-pump-loop.sh
- lib/oref0-setup/alias.json
If the pumphistory pull (plus everything else in between the clock pull and the pump clock check in oref0-pump-loop) takes longer than 1 minutes, the pump clock check will fail per #477.  This should help alleviate that, hopefully eliminated the repeated NewTimeSet condition even with slow rigs or flaky pump comms.
> check pump clock after pumphistory to alleviate #477 race condition

- lib/bolus.js
- lib/meal/history.js
- tests/cobhistory.test.js
This needs to be tested by someone with a pump that is capable of writing carb-only bolus wizard records when you cancel out of the bolus wizard or enter a zero bolus.
Test procedure:
- Enter a small number of carbs via the bolus wizard.  Cancel out or enter a zero bolus.  Make sure that the carbs show up in NS and in meal.json.
- Check out this branch: `cd ~/src/oref0 && git fetch && git checkout ignore-carb-corrections && git pull`
- Enter another small number of carbs the exact same way as before.  Make sure the carbs do *not* show up in NS or in meal.json.
- Enter a small number of carbs with a minimal bolus (0.1U or whatever your pump supports).  Make sure those show up normally.
- Test out other normal scenarios and make sure they all still work.
> per #419, ignore bolus wizard carb entries without a bolus

- bin/oref0-pump-loop.sh
- lib/meal/total.js
- lib/oref0-setup/report.json
and use pumphistory-merged.json for COB calculations in meal.json
This should help ensure that the insulin dosing history used to calculate historical carb absorption is always complete, which hopefully will eliminate zombie reappearing carbs.
> merge_pumphistory to fix zombie carbs

- bin/oref0-get-profile.js
- lib/determine-basal/determine-basal.js
- lib/profile/index.js
In oref1 testing so far, nearly all complaints have been about it not dosing enough insulin after meals, and almost everyone has ended up raising remainingCarbsCap and remainingCarbsFraction.  This would change the defaults there to be the same as the max limits: 100% of 90g.
Also incorporates #511
> Update default preferences

- bin/oref0-pump-loop.sh
add the get CGM data from MDT into pump-loop.sh
removes the Alias calls for getting the cgm data from the pump
fixed the grep for MDT so that it does not show the Printout of the Alias every time the script checks for MDT 
I made it so that when it does get the data from the pump, if it fails due to a decocare error
"decocare.errors.DataTransferCorruptionError: Page size too short"
I did never realize this before while it was in the Alias that this happens a lot, normally when it does fail if you just try to run it again it fixes and works fine, So I've made it so it can fail 3 times. I've never seen it have to run more than twice. 
Also have the loop check the time stamp on monitor/cgm-mm-glucosedirty.json after getting data if it is not any newer than the data already received, there is …
> Add MDT to pump-loop.sh

- bin/oref0-pump-loop.sh
- lib/bolus.js
To fix #524, this reverts the portion of #512 that disabled the upload of carb-only bolus wizard entries, which looks to be independent of the changes to oref0-meal that ignore such entries for purposes of calculating COB.
We'll need to test that a carb-only bolus wizard entry when there's no COB does not end up contributing to COB via getting uploaded to NS and then downloaded again into carbhistory.json.
> upload carb-only bolus wizard entries to NS again

- lib/oref0-setup/report.json
This should allow the pumphistory refresh to complete more quickly and more reliably without missing any data (since pumphistory-24h can never be more than 2h old).
> only pull 2h of pumphistory now that we merge it with pumphistory-24h

- bin/oref0-setup.sh
Not yet tested.  To test:
```
cd ~/src/oref0
git fetch
git checkout oref0-pump-loop
npm run global-install
```
and run oref0-runagain or oref0-setup again.
> switch non-SMB users over to oref0-pump-loop

- bin/oref0-pump-loop.sh
- bin/oref0-setup.sh
- lib/determine-basal/determine-basal.js
- lib/oref0-setup/alias.json
This avoids a corner case where both pumphistory files are old and the pumphistory-merged.json gets created before pumphistory-24h.json is refreshed, and then the rig miscalculates COB for a few minutes until pumphistory is refreshed again.
> various oref0-pump-loop fixes affecting COB calculation

- lib/determine-basal/determine-basal.js
- tests/determine-basal.test.js
This closes a potential loophole that could be used (if you somehow got a target_bg into profile.json) to bypass the safety checks on target_bg being >=80 and <= 200 mg/dL.
I don't think this is what Miiko saw at https://gitter.im/nightscout/intend-to-bolus?at=59655496c101bc4e3a764ecf, but it's the only code path I could see that would bypass those checks.  And since no one has ever explicitly set target_bg AFAIK, it'd be better to remove that code anyway, and update the few tests that use it to use min_bg and max_bg instead (which this PR also does).
> don't use profile.target_bg, just min_bg and max_bg

- bin/oref0-pump-loop.sh
This moves unsuspend_if_no_temp somewhere it can actually be executed.  Prior to this change, zero-duration (finished) zero temps were causing smb_verify_enacted to fail before it ever got to smb_check_everything.
> Fix unsuspend

- bin/oref0-setup.sh
This fixes a missing `fi` that is breaking oref0-setup, and all the messed-up indentation whitespace that contributed to my thinking it wasn't needed when I did the merge conflict resolution (plus some other indentation stuff that was making it hard to find the missing `fi`).
Will need to do a patch release of this.
> Fix missing fi

- lib/oref0-setup/report.json
Dunno how we missed this in dev, but without this change it looks like everyone's IOB calculations are being truncated at 2h per https://github.com/openaps/oref0/issues/554, so we'll need to test this and release it to master as a patch release.
> use pumphistory-merged.json for IOB calculations

- bin/oref0-setup.sh
install decocare with setuptools since 0.0.31 (with the 6.4U/h fix) isn't published properly to pypi, so openaps only pulls 0.0.30
> easy_install -U decocare

- bin/oref0-setup.sh
small fix. make decocare work on a rpi.
tested ok.
please merge.
> use sudo to install it decocare with easy_install. This is required for installing it on rpi. 

- bin/oref0-setup.sh
Found this while looking for what might be causing the `SyntaxError: /root/myopenaps/preferences_from_args.json: Unexpected token .` error some people are reporting on FB. 
This might be contributing to it, or it might be unrelated, not sure.  Will need someone who can reproduce the original problem to test this as a possible fix.
> fix &current_basal_safety_multiplier typo

- bin/oref0-pump-loop.sh
This should help avoid scary warning messages for folks not using Explorer boards, per https://github.com/openaps/oref0/issues/552#issuecomment-316219411
> only reset_spi_serial.py if [[  == /dev/spidev5.1 ]]

- lib/determine-basal/determine-basal.js
- lib/profile/index.js
With shorter DIAs and large meals with undercounted carbs, COB often decays to 0 before carb absorption finishes, and UAM cuts off after DIA hours.  This preference, if enabled, would allow UAM to remain active and allow oref1 to SMB if needed for 6 hours after any carb entry, unless disabled by a high temp target.
> enable SMB/UAM for a full 6 hours after any carb entry

- bin/oref0-autotune-export-to-xlsx.py
Path references were from the openaps directory, rather than from the autotune directory as the helper text asks for.
> Change filepath reference points

- lib/iob/calculate.js
- tests/iob.test.js
Rather than figure out how to modify the IOB formula, we can simply set t = t * profile.bolussnooze_dia_divisor and then use the same formula again with the new value of t.  This will cause us to find the point twice as far along the IOB curve, achieving the same things as we currently do for the bilinear curves, of making bolus snooze IOB decay twice as fast as "real" IOB.
Needs testing.
> simply calculate biobContrib using 2t instead of t

- lib/bolus.js
- tests/bolus.test.js
**Why is this needed?**
Boluses, especially with SMB, may arrive spaced very closely together.  The current bolus pre-processing will combine these with bolus wizard records to generate synthetic records containing portions of the various records.  Instead of adding additional boluses that occur with a bolus wizard matching window (5 minutes), it simply uses the first that occurred after a bolus wizard record.  That was incorrect behavior.
**What is this doing?**
The bolus-wizard matching window is being shortened to 2 minutes, which is long enough to avoid some nightscout deduplication behavior that can lead to missed records.  Within the 2-minute window, any boluses are added together so the totals match reality, even if the event sequence doesn't exactly match pump history.  The total …
> Fix handling of closely-timed boluses

- package.json
Since day 1, the `openaps` toolkit has used `git` to provide full auditability of every file whose contents are controlled by `openaps`. This has definitely been useful, especially in the early years when we were troubleshooting lots of bugs in the openaps toolkit and with peoples' custom aliases and reports. Since we've standardized everyone's openaps setups with oref0-setup, though, we've found that the need for json-file auditability has greatly diminished, to the point where I think it's been almost a year since we relied on the openaps git history for troubleshooting an issue. Instead, we either run openaps commands manually to reproduce an issue, or look at the pump-loop.log or other log output to see what was happening if there was an issue that is no longer occurring. This …
> Stop using ~/myopenaps/.git/

- lib/meal/total.js
This should help eliminate one source of zombie carbs by forcing mealCOB to 0 until we have enough data to properly calculate deviations.
> if currentDeviation is null or maxDeviation is 0, set mealCOB to 0

- lib/determine-basal/determine-basal.js
- lib/meal/total.js
https://github.com/openaps/oref0/blob/smb-lgs/lib/determine-basal/determine-basal.js#L564-L568 skips low glucose suspend if IOB is already super negative and BG is rising faster than predicted. However, while it's useful to be able to avoid extended zero temping in that situation, it's best to avoid SMBs until BG has risen above the LGS threshold.
> don't SMB unless bg > threshold

- lib/determine-basal/cob-autosens.js
- lib/iob/index.js
Profiling lib/meal showed that most of the multiple minutes required to calculate IOB was spent in lib/iob/history continually re-parsing pumphistory into treatments for every 5m BG data point and for every carb treatment.  Since the contents of pumphistory are unchanged no matter which treatment or entry we're considering, we can instead just parse pumphistory into treatments once and then pass the result on each get_iob run.
This reduces time spent calculating meal.json by a factor of 5x 
pi@pi2-erf ~/myopenaps $ cd ~/src/oref0/ && git checkout 0.6.0-dev && cd ~/myopenaps && time openaps report invoke monitor/meal.json && cat monitor/meal.json && cd ~/src/oref0/ && git checkout optimized-cob && cd ~/myopenaps && time openaps report invoke monitor/meal.json && cat monitor/meal.json …
> Speed up COB calculation by only converting pumphistory to treatments once

- lib/determine-basal/cob-autosens.js
- lib/iob/index.js
We have been doing a bunch of unnecessary future IOB calculations in the COB calculation subroutine when all we really need at that point is the current IOB.  This passes a flag to get_iob() to tell it not to bother with all that when we're just going to throw away the results anyway.
My `time openaps report invoke monitor/meal.json` run (on an Edison with lots of treatments) went from 1m59s to 1m17s with this change.  Everything still seems to be working normally after a few completed loops.
> speed up COB calculation

- bin/oref0-pump-loop.sh
Number one error for beginners that blocks looping is when people don't have the pump set to absolute u/hr (in % basal type instead), which prevents the rig from being able to set temp basals.
(Note: needs testing)
> Calling out the number one beginner error

- bin/oref0-pump-loop.sh
- lib/determine-basal/cob-autosens.js
- lib/oref0-setup/alias.json
Currently oref0-meal takes a long and variable amount of time to run.  Running as part of the monitor-pump alias, the meal.json report also runs after merge_pumphistory, which means it's working with old data.  We should instead run it separately.  For now I'm leaving it as part of the gather function, but at some point we may want to pull it out into ns-loop or something.
> Separate out meal calcs from monitor-pump alias

- lib/determine-basal/determine-basal.js
We currently calculate CSF in determine-basal using autosens-adjusted ISF divided by carb ratio.  This means that we end up mostly counteracting the autosens ISF adjustments when doing OpenAPS-controlled meal dosing (via SMBs or high temps).  For example, if ISF is 40 mg/dL and CR is 10 g/U, normal CSF would be 4 mg/dL/g.  If the PWD is running sensitive and has an autosens-adjusted ISF of 60, then recalculating CSF to be 6 mg/dL/g would result in us trying to deliver 1U of insulin for every 10g of carbs (CR of 10 g/U) despite the higher ISF.  Only as COB starts to decay would we back off and start honoring the higher ISF by trying to reduce IOB.
This change should result in OpenAPS dosing more conservatively (high-temping and SMBing less, and/or low-temping more) after meals when …
> honor autosens-adjusted ISF at meal-times

- lib/determine-basal/determine-basal.js
When deviations are high after a meal and BG ticks downward due to CGM noise, we'll often see an immediate carbsReq notification (and aggressive zero temping) from the now-negative deviations.  Rather than (encouraging the user to) overreact to negative deviations from a single data point, I think it would be better to use a longer averaging interval in that case.  We already do this by switching to the minAvgDelta (the lower of short_avgdelta and long_avgdelta): this further extends that logic to use long_avgdelta if minAvgDelta results in a negative deviation.
As a result of this change, oref0 will also be slightly slower to zero temp when BG unexpectedly starts dropping, but will still stop SMBing / high temping immediately (and will still zero temp if in SMB mode).  And if it isn't …
> don't overreact to negative deviations from a big negative delta

- bin/nightscout.sh
- lib/oref0-setup/report.json
This PR is a temporary fix to address an issue with temp targets and carb histories extracted from NS. There is an inconsistency with the `created_at` field where entries made through Care Portal have `created_at` in UTC, while entries uploaded from oref0 have `created_at` in local time. The simple string compare used in the query is not timezone aware. (See https://github.com/openaps/oref0/issues/600 for discussion on this.)
- `bin/nightscout.sh` has been modified to use UTC time in the query string for both `temp_targets` and `carb_history`
- `lib/oref0-setup/report.json` has been modified to use a lookback of 18 hours for `monitor/carb_history.json` (so that users at UTC -12 will still get 6 hours of data for entries with `created_at` in local time)
Note that I'm assuming temp targets …
> Fix for missing temp targets and carb treatments for timezones east of UTC

- bin/oref0-pump-loop.sh
If the pump gets suspended while an SMB is being delivered, the pump remains in bolusing status until the pump is resumed, at which time the bolus delivery is completed.  This state caused our pumphistory Refresh check to fail, which meant that the rig would have been unable to unsuspend the pump if necessary.  By ignoring the bolusing status if the pump is suspended, we can proceed to pull pumphistory and check temp basal duration, and unsuspend the pump if the temp basal expires.
> ignore bolusing status if pump is suspended

- bin/oref0-get-profile.js
Per https://github.com/openaps/oref0/issues/590, preferences.json is still displaying all defaults in some cases.  This would force it to only add in displayedDefaults.  If someone wants to change a non-displayed default, they'll have to add it to preferences.json manually.
> only updatePreferences with displayedDefaults

- lib/determine-basal/determine-basal.js
- lib/iob/index.js
Per https://github.com/openaps/oref0/issues/619#issuecomment-323494069, current oref0 code models any carb absorption that hasn't yet begun as a constant value over the next 4 hours, such that, for example, a 120g meal would have a remainingCI equivalent to a constant 30g/hr for the next 4 hours.
This changes remainingCI from a constant to a bilinear curve that increases from 0 to a peak absorption rate (in g/h) of remainingCarbs/2, and then symmetrically decreases back to 0 at the 4h mark.
So if you entered 120g of carbs and had zero absorption so far, this change would cause oref0 to model absorption starting at 0, increasing to 30 g/h after 60m (1h), 60 g/h after 120m (2h), then back to 30 g/h after 180m (3h), and 0 g/h after 240m (4h). The average carb absorption over hours 1 and 4 …
> model remainingCarbs as a /\ shaped bilinear curve

- bin/oref0-setup.sh
Local (offline) looping hasn't been working on my rig since the latest update from dev. Turns out the script is called from crontab with extension `.sh` (`monitor-xdrip.sh`), which cannot be found. This commit removes the filename extension in consistency with other bash scripts called from crontab.
Note: this fix requires re-running `oref0-setup.sh`.
> fix monitor-xdrip

- bin/oref0-pump-loop.sh
If a rig hasn't mmtuned or completed a pump-loop recently and fails to loop, it's probably best to do an mmtune.  Setting "recently" to 15m for now.
> mmtune on failure if pump_loop_completed > 15m old

- bin/ns-get.sh
- bin/oref0-autotune.sh
The change in #578 to use ns-get instead of directly using curl broke the time based filters that autotune uses to limit its data download, because ns-get uses curl's `-g` flag.  This caused autotune in 0.5.3 dev to run extremely slowly (due to all the extra treatments) and to erroneously autotune with multiple days' worth of data each day.
> URL encoding for autotune filters

- bin/oref0-pump-loop.sh
- lib/determine-basal/determine-basal.js
Rather than oscillating back and forth between a 30m zero temp and a neutral temp, this allows SMB to set an intermediate low temp when less than 30m of zero temping is required.
> Allow nonzero low temps for SMB

- lib/determine-basal/determine-basal.js
After a long period of zero temping and rescue carb rebound, COB had decayed to zero, but BG was still rising sharply and IOB was still < 0 when the rescue carb temp target expired and SMBs kicked back in.  As a result, an SMB of 1U was given, rather than being limited to 0.6U, contributing slightly to a later low.
This change would keep the maxSMBBasalMinutes at 30 any time IOB (and COB) are <= 0, thereby preventing large microboluses solely based on UAM when IOB is negative.
> don't allow maxSMBBasalMinutes > 30 unless IOB (and COB) are > 0

- lib/meal/total.js
Since the original mealAssist days, the `carbs` value in meal.json, also known as `mealCarbs` in some files, has contained the total number of carbs seen in the last 6 hours or so.  When using this value in determine-basal to blend COB and UAM, it would be better if `carbs` value only contained those carbs used in calculating the current COB value, and ignored carbs from previous meals that had fully expired before the current meal (and weren't stacked on top of it).
This change removes from `carbs` any carb values that don't end up getting used in COB calculation.
> carbs: should only include carbs actually used in calculating COB

- lib/determine-basal/determine-basal.js
We currently calculate avgPredBG as the straight average of IOBpredBG + UAMpredBG + COBpredBG when all three are available.  In order to be a bit more aggressive at dosing more insulin up front when COB is entered, and then a bit less trusting of the COBpredBGs once COB has decayed a bit, this change would weight COBpredBG vs. UAMpredBG based on how many carbs remain as COB, as we do for blendedMinPredBG.
> Trust COB a bit more until it decays

- lib/determine-basal/autosens.js
Per https://github.com/openaps/oref0/pull/629#issuecomment-327127003, now that autosens is properly excluding meals based on IOB and COB, we no longer need to exclude deltas >= 6 mg/dL from autosens calculations.
> remove autosens avgDelta-bgi < 6 check

- bin/monitor-xdrip.sh
`monitor-xdrip.sh` fails sometimes because `$directory` is null. It looks to be set in the autotune script [here](https://github.com/openaps/oref0/blob/92919bde860f438556e916e5c6a2c355d5006194/bin/oref0-autotune.sh#L79) so will be undefined if autotune hasn't run.
All of the other `cp` commands in the script work fine without it; as should this one.
> remove  variable

- bin/oref0-autotune-prep.js
- bin/oref0-autotune-recommends-report.sh
- bin/oref0-autotune.sh
- bin/oref0-pump-loop.sh
- lib/autotune-prep/categorize.js
- lib/autotune-prep/dosed.js
- lib/autotune-prep/index.js
- lib/autotune/index.js
Currently autotune categorizes glucose deviations data into buckets based on what is impacting things the most: basals, carbs, or insulin.  It uses the mealtime data to calculate CSF, the IOB-without-COB data to calculate ISF, and then the remainder to adjust basals.  This works fairly well, but due to the fuzzy line between carb-dominated and insulin-dominated deviations after a meal, it tends to overestimate ISF.  CR is calculated as ISF/CSF, so that tends to be overestimated as well.
As an alternative, this change calculates CR directly.  To do so, we use the BG and IOB at the time of carb entry, the BG and IOB after COB==0 and IOB is back down to low level, the total amount of carbs given, and the total amount of insulin given over the meal period.  After adjusting for the BG and IOB …
> Autotune: calculate CR directly

- lib/determine-basal/determine-basal.js
Even with the new bilinear /\ shaped carb absorption curve, some meals spike more quickly than the assumed 4h, so it would be better to provide the user a way to tell the system that an upcoming meal is likely to be fast-absorbing, and allow oref1 to more aggressively SMB for the predicted rise.
To do so, this change adjusts the duration of the /\ remainingCI absorption curve to be shorter (3h) when a temp target of 80 is set, and longer for a high temp target (5h for 120, 6h for 140, etc.).  This gives the user more control over how aggressive they want SMB to be for carbs that have been entered but aren't yet absorbing.
> Make remainingCI time responsive to temp targets

- lib/determine-basal/determine-basal.js
Prior to this change, a not-very-high temptarget (like 110) could be adjusted below 100 by a sufficiently high BG, causing SMB to kick in unexpectedly.  This prevents temptargets from being adjusted by adv_target_adjustments.
> don't adjust temptargets for high BG

- lib/determine-basal/determine-basal.js
Fixes a cosmetic bug that resulted in NaN being displayed in pump-loop.log when CI is exactly zero:
```
Carb Impact: 0 mg/dL per 5m; CI Duration: NaN hours; remaining CI (2h peak): 0 mg/dL per 5m
Accel. Carb Impact: 10 mg/dL per 5m; ACI Duration: 0 hours
predCIs: NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN
remainingCIs: 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
COB: 0 remainingCItotal/csf: NaN remainingCarbs: 0
```
> avoid divide by zero (NaN) in CI Duration

- bin/oref0-pump-loop.sh
Discovered some issues in 0.5.3 that caused issue for 512/712/x12 users.
Includes:
- Confirmation that x12s will not work with SMBs
- Better error messaging around x12 model checks
- Other bugs that were preventing x12s from working successfully
> 512 support

- lib/profile/index.js
Since there are no strings displayed in preferences.json by default, it's non-intuitive to know how to add "curve".  Since we'll eventually want everyone to change over to an exponential curve (and most likely will eventually want to make "rapid-acting" the default and deprecate "bilinear"), we should include "curve" in displayedDefaults.
> display curve in preferences by default

- lib/determine-basal/cob.js
- lib/determine-basal/determine-basal.js
- lib/meal/total.js
In 0.5.3, UAM assumes that current deviations will only decrease to zero over 3 hours if the currentDeviation exceeds the maxDeviation over the last ~45m.  This means that the UAMpredBG purple prediction line goes way too far up-and-to-the-right when carb absorption is peaking.  As an alternative to make UAM safer / less aggressive in that situation, this change causes UAM to assume that current deviations will ramp down over time proportional to how quickly they've ramped up from the recent (~45m) minimum deviations.  So if deviations are rising rapidly due to fast carbs, UAM will not project that to continue indefinitely, but typically only for 1-2h.  For meals whose carb absorption ramps up more slowly, the minDeviation will be higher, and a slower ramp down will be projected as well. …
> Less aggressive UAM

- bin/oref0-pump-loop.sh
If the time of a rig running without SMB doesn't sync on boot-up and is therefore reading way in the past, the monitor/pumphistory-zoned.json file will be way in the future (2017 vs. 1969/1970), which causes refresh_pumphistory_and_enact to think nothing needs to be done, and thereby never gets to the `grep incorrectly enact/suggested.json && oref0-set-system-clock 2>/dev/null` line in the `enact` function.  This should force it to consider as "old" a future-dated pumphistory-zoned.json and proceed with the loop.
To test, boot up a non-SMB rig without Internet while watching pump-loop.log on console, and verify that you see it proceed to try to re-sync NTP and then set the system clock from the pump clock when that fails.
> proceed to enact and set clock if pumphistory-zoned is in the future

- bin/oref0-detect-sensitivity.js
- lib/determine-basal/autosens.js
This calculates the autosens ratio twice, once using the most recent 8h worth of non-excluded data (which during the day ends up being 12h+ due to meal exclusions), and once using up to 24h of non-excluded data (usually closer to 16h due to meal exclusions).  It then uses the lower (more sensitive) of the two ratios.  This improves safety by allowing for faster response to increased sensitivity, while responding more slowly to increased resistance.
> calculate autosens ratio with both 8h and 24h of data

- bin/oref0-pump-loop.sh
- lib/determine-basal/determine-basal.js
This change calculates a minGuardBG value, based on the lowest predicted COB value (starting from now, not from 60-90m in the future as other predBGs do) if COB is present, or the lowest predicted UAM value if that's present, or the lowest IOB predBG if neither COB nor UAM is available.  If the minGuardBG is below threshold (the same one used to decide not to high temp), then SMBs are temporarily disabled.
> disable SMB if predicted BG drops below threshold

- bin/oref0-pump-loop.sh
We currently allow oref0-pump-loop to try to set a temp basal before it tries to refresh pumphistory if it hasn't completed a pump loop recently, as a way to make sure that we can enact temp basals based on updated BG data even when pump comms are flaky.  However, this results in high temps being set and then immediately canceled when an SMB has been delivered that the rig doesn't know about yet.
This change skips the "setting temp before refreshing pumphistory" code path if the currently running temp basal has a duration of more than 20 minutes.
This also makes oref0-pump-loop refresh pumphistory after bolusing or enacting a temp, so we don't have to wait 5 minutes for it to be displayed in NS.
> Refresh pumphistory before setting temps and after SMB/enact

- bin/oref0-setup.sh
As noted in https://github.com/openaps/oref0/issues/630, I've never seen mmtune run sooner than on the fourth time through the loop after rebooting. Removing `pump_loop_completed` on reboot makes the loop run mmtune on the first loop, decreasing non-looping time from about 25 minutes after reboot to a little under 10 minutes.
> Remove pump_loop_completed on reboot to make mmtune run sooner

- bin/oref0-pump-loop.sh
Proposed changes to the location of pump_loop_completed from $directory/monitor/ to /tmp/ so it disappears after reboot. Please double check lines 367, 474, and 529 since I'm not super up on Bash scripting?
> Put pump_loop_completed in /tmp/

- bin/oref0-pump-loop.sh
Now that we're refreshing pumphistory after each loop, the only things remaining out of date until the next one are the IOB pill and purple prediction lines.  This recalculates those so they can be uploaded as well.
> recalculate IOB and predBGs after each loop

- lib/determine-basal/cob.js
- lib/meal/total.js
This displays an allDeviations array in pump-loop.log (from meal.json) to help see what UAM is doing and why.
`{"carbs":30,"mealCOB":6,"currentDeviation":6.49,"maxDeviation":10.02,"minDeviation":6.44,"slopeFromMaxDeviation":-1.325,"slopeFromMinDeviation":0.03,"allDeviations":[6.49,6.44,8.02,8.89,10.02,8.46,6.84,7.81]}`
> add allDeviations to meal.json output for UAM monitoring

- lib/determine-basal/determine-basal.js
minPredBG was displayed twice in the suggested.json, once at the top level and once as part of the reason field.  The top-level object was not always updated correctly.  This removes the duplicate.
> remove extra minPredBG in rT object

- bin/oref0-autotune-recommends-report.sh
- bin/oref0-autotune.sh
- lib/autotune-prep/categorize.js
- lib/autotune/index.js
- lib/profile/index.js
This fixes an upward bias in the new CR autotuning from dinners that don't finish absorbing by midnight, and removes the upward bias on ISF from ignoring (slightly) positive deltas.
It also fixes a bug that was preventing ISF data from being capped by the min/max limits before being applied, and only capping it afterward.  Fixing that allows us to stop relying on the autotune ISF adjustment ratio hack, so it changes the default value to 1.0 (in preparation for removing it entirely at some future date).
CSF is also removed from the recommendations report to reduce confusion now that ISF and CR are both calculated directly (and somewhat independently).
> autotune de-biasing

- bin/oref0-pump-loop.sh
I'm still seeing occasional instances where two rigs get all the way through to issuing small SMBs at the exact same time.  (SMBs larger than about 0.2U take too long to be an issue.)  This randomizes the wait_for_silence before smb_verify_reservoir to be $upto10s to try to make sure that other rigs are done talking before we do our reservoir check to see if any other rig has just SMB'd > 0.1U.
> randomize wait_for_silence before smb_verify_reservoir

- lib/determine-basal/determine-basal.js
- lib/meal/total.js
Using fractionCOBAbsorbed to calculate remainingCATime works well for meals where all the carbs are entered up front, but tends to be too slow to bolus for additional carbs entered later.  This changes the remainingCATime to be calculated based on the remainingCATimeMin (usually 3h) plus the time since the last carb entry, so that when additional carbs are entered, it resets the clock and assumes that they (and any remaining COB) will absorb over 3h.
> use lastCarbAge to calculate remainingCATime

- lib/determine-basal/determine-basal.js
- lib/profile/index.js
We often see non-meal-related rises that benefit from SMB/UAM correction.  For people who have been running SMB long enough to be comfortable running it overnight, this provides an option to enable such corrections 24x7 (except when overridden by a high temp target).  This is *not* recommended for new users, so it will not be exposed in displayedDefaults.
> add an enableSMB_always option

- lib/determine-basal/determine-basal.js
originally we were waiting 90m before setting minPredBGs in order to be sufficiently aggressive at bringing down BGs predicted to ramp up quickly from meals.  When experimenting with shorter remainingCA carb absorption times we shortened the minPredBG lookahead to 55m+15m=70m for Fiasp, leaving rapid-acting insulins at 75m+15m=90m.  This extends that another 15m, to 85m for Fiasp and 105m for RAIs, which will allow eSMB to be more aggressive at mealtimes, as seems to be necessary to accomplish no-bolus (carb guesstimate only) looping with Fiasp with 80% time in range.
> look ahead an additional 15m to get insulin started faster

- bin/openaps-bootstrap.sh
This just updates the oref0 copy of openaps-bootstrap.sh to match what's in the OpenAPS docs.  So far nothing  is using this copy yet.
> curl openaps-install.sh

- bin/oref0-pump-loop.sh
- lib/oref0-setup/alias.json
If a rig is getting too hot, we should pause pump-loop and ns-loop (the two that drive most CPU activity) until the rig cools off, while printing error messages in pump-loop.log to inform the user they need to better ventilate their rig.  This will allow the rig to set temps at least occasionally, rather than getting to the Edison's critical temperature alarm threshold and rebooting (or presumably shutting down hard at some point).
This has been tested on a well-insulated overheating Edison rig by pulling the updated oref0-online and manually updating openaps.ini. We'll also need to make sure that the alias.json change doesn't break anything, and that checking `sensors` doesn't break anything on Pi rigs that don't have it.
> don't run loop if rig is too hot

- bin/oref0-setup.sh
Thanks to the amazing @Kdisimone as always for the first round of testing, confirmed it successfully installs and removes an existing git directory.
Looks like this after starting setup:
And then it successfully removed .git
For anyone else who wants to test:
1. `cd ~/myopenaps` and `ls -la` (you should see .git listed in the alphabetical list - we need this tested on rigs that still have git)
2. `cd ~/src/oref0/ && git fetch && git checkout no-git-default && git pull`
3. `npm run global-install`
4. `bash ~/myopenaps/oref0-runagain.sh`
5. Once done, `ls -la` again in `myopenaps` and confirm that .git no longer exists there.
*(If you're planning to stay on this branch vs. switching back to dev, make sure to re-set your preferences!)*
> Attempting to --nogit by default for existing user installs

- lib/determine-basal/determine-basal.js
Rather than using a hard cutoff of 75% of carbs to switch minGuardBG over from COBpredBGs to UAMpredBGs, this calculates a minGuardBG for each of COB, UAM, and IOB, and blends the minCOBGuardBG and minUAMGuardBG according to what % of carbs have absorbed.  This allows oref0 to be less aggressive (particularly with SMBs) when carbs are overestimated or CR is too low and UAMpredBGs are running much lower than COBpredBGs.
@PieterGit this one might also be helpful for you.
> Blend minGuardBG

- bin/oref0-pushover.sh
Previously, if a rig sent a pushover, then generated a new smb-suggested.json, and then stopped looping (because the pump walked away), it would send one more pushover alert with the last calculated carbsReq (and an old BG value) after 15m.  This instead forces the smb-suggested.json to be current (<5m old) to generate a pushover alert.
> Don't send stale pushovers

- lib/determine-basal/determine-basal.js
Per @PieterGit the current 0.6.0-dev code seems a bit too aggressive in some situations for some users on rapid-acting insulin.  In order to make it somewhat less aggressive, this reverts some changes that attempted to tie the minPredBG lookahead (where we ignore the first X minutes of predBGs when setting minPredBG) to the insulinPeakTime, and therefore makes eSMB less aggressive for non-Fiasp users.
Would like to hear input from others using SMBs with rapid-acting insulin and discuss if this is a change we want to make, or if it would make eSMB less effective and perhaps we should focus elsewhere.
> Go back to using a 90m minPredBG lookahead for all insulin types

- lib/determine-basal/autosens.js
- lib/determine-basal/determine-basal.js
- lib/iob/history.js
- lib/profile/index.js
As described in https://github.com/openaps/oref0/issues/588 and https://github.com/LoopKit/Loop/issues/593, OpenAPS activity mode doesn't do enough (at reasonably low temp target levels) to handle extended aerobic exercise, and often overshoots if you set the temp target high enough to do so.  This implements a better approach, which uses the level of the temptarget to set a manual sensitivityRatio.  This is used the same way as the autosens ratio, to set the basal and ISF used for current decisions.  In addition, it also is used to set the basal used by IOB calculations, such that setting an activity mode raises OpenAPS' estimate of IOB, and causes it to zero temp long enough to get IOB down to a level more suitable for aerobic activity.
These extra adjustments kick in for temp targets > …
> Exercise mode

- lib/determine-basal/cob.js
- lib/meal/total.js
This fixes a bug in COB calculation that was causing COB to decay to zero too quickly (and in other cases can cause it to decay too slowly) when carbs were entered during a sensor restart or other BG data gap.
> fix BG interpolation for COB calculation

- bin/oref0-pushover.sh
- lib/determine-basal/determine-basal.js
- lib/meal/history.js
The current carbsReq notifications tend to be too sensitive when carbs aren't likely to be needed for an hour or more.  This changes the carbsReq calculations to be based on how much time BG is predicted to remain above the minGuardBG threshold (which comes out to 70 for a target of 100).  It uses naive_eventualBG so as not to be too sensitive to current BG slope, and attempts to make sure that there will be enough time for zero-temping to get IOB down to zero by the time BG hits the threshold.  If there is not, it will recommend enough carbs to compensate, and also note how soon they'll likely to be needed, so the user can decide whether to do carbs right away or wait and see if BG flattens out on its own and they're not actually needed.
This also disables insulinReq pushover …
> Time-aware carbsReq

- bin/oref0-pump-loop.sh
When an SMB pump-loop finishes right before a new BG comes in, the next SMB can't be issued unless it's been 2 minutes since the last bolus.  Previously, that would result in that SMB being skipped, and the rig waiting for the next BG after that to get back on schedule.  This allows oref0-pump-loop to skip the wait for new BG if it's waiting to do an SMB.
> Retry microbolus before next BG if needed

- bin/oref0-determine-basal.js
- bin/oref0-pump-loop.sh
- lib/determine-basal/determine-basal.js
- lib/iob/index.js
@hilarykoch recently experienced an A52 error that rebooted the pump and somehow caused decocare/openaps to prematurely stop parsing pumphistory such that it didn't return an error but didn't include recent events.  This in turn resulted in incorrect IOB, causing OpenAPS to overdose insulin, providing Leo with an unscheduled pump break and dessert.
This PR adds some safety checks to make sure that pumphistory is being updated, and that the lastTemp in pumphistory matches the currently running temp basal on the pump.
> Pumphistory safety checks

- lib/determine-basal/determine-basal.js
We added a safety check to avoid SMBing when delta is >10% of BG, in order to avoid overreacting to a noisy sensor, calibration jump, or other "fake" rise.  However, that threshold also prevented SMBing when it's needed most: when BG is rising fast from uncovered fast carbs.  This changes the threshold to 20%, which we've found is sufficiently high to allow SMBs when really needed.
> raise SMB-disable threshold to > 20% of bg to catch fast carb rises

- lib/determine-basal/determine-basal.js
Per https://gitter.im/nightscout/intend-to-bolus?at=59e44ad9614889d475bcf91b @mackwe was seeing excessive zero temping after meal carb entry.  Turns out minGuardBG was getting set based on minIOBGuardBG instead of minCOBGuardBG due to a logic flaw.  This should fix that.
> fix logic fail for ! enableUAM case to set minGuardBG from COB

- bin/oref0-html.js
- bin/oref0-pebble.js
- bin/oref0-setup.sh
- bin/peb-urchin-status.sh
- lib/determine-basal/determine-basal.js
- lib/iob/calculate.js
- lib/iob/total.js
- lib/profile/index.js
- tests/determine-basal.test.js
- tests/iob.test.js
With eSMB now allowing no-bolus operation of OpenAPS, the distinctions between manual boluses and microboluses are breaking down, which prevents things like bolus snooze, which assume that automatically administered insulin should be classified as basal insulin / IOB and kept distinct from bolus insulin / IOB.
Now that carb ratios can be properly autotuned, carb absorption is assumed to occur over less than DIA, the original need for bolus snooze is largely eliminated.  The only remaining need for it might be if anyone is not entering carbs (either via NS or the pump), is manually bolusing for food, and then is expecting bolus snooze to cover until UAM kicks in.  If that turns out to be a significant fraction of the OpenAPS user base (which I doubt) we can revisit how best to support that …
> Eliminate basal vs. bolus distinctions

- .gitignore
- bin/oref0-ns-loop.sh
- bin/oref0-pump-loop.sh
- bin/oref0-radio-reboot.sh
- bin/oref0-setup.sh
- lib/oref0-setup/report.json
- package.json
Refactor `openaps ns-loop` into its own shell script, oref0-ns-loop.sh, and improve ns-loop logging significantly.
Also includes a fix for Pi Explorer HAT support, and some minor logging improvements to oref0-pump-loop.
> oref0-ns-loop

- bin/oref0-setup.sh
If Bluetooth is already installed, oref0-online will attempt to start it back up while we're downloading and making bluez (to upgrade it per #724).  This change adds another killall bluetoothd again immediately before trying to install the newly compiled binary to prevent the copy from failing.
> Fix bluez upgrade

- bin/oref0-pump-loop.sh
Per https://github.com/openaps/oref0/issues/720 the recently added safety checks caused a regression for users of the non-SMB pump-loop.  To fix that, and make sure that future changes to oref0-pump-loop are more thoroughly tested, this deprecates the old pump-loop and consolidates both SMB and non-SMB use cases onto the one formerly known as smb_pump_loop.  The actual bolus commands are not executed if --microbolus is not passed, but everything else is done the same for both loop types.  This results in some extra status checks for non-SMB users, but that shouldn't hurt anything, and helps avoid problems like we saw with the safety checks making assumptions about the state of various data files that weren't met when the basal-only pump-loop did things in a different order.
> fix broken safety checks with a single pump-loop type

- bin/ns-get.sh
@cbrenner reported at https://gitter.im/nightscout/intend-to-bolus?at=59e6566ad6c36fca31635aeb that his rigs have been losing connectivity and ns-loop has been getting stuck and not recovering, stopping his loop.  This is likely because a curl gets into a state where it never completes until timing out.  We already limit ns-upload curls to 30s, so this does the same for ns-get.
> timeout ns-get curls after 30s

- bin/oref0-setup.sh
MDT CGM relies on a custom ns-loop.  Until we update oref0-ns-loop to support that, we'll want to keep using the old one for MDT CGM users for now.
> use old ns-loop for MDT CGM for now

- bin/openaps-install.sh
- bin/oref0-setup.sh
An attmept to reduce problems on Pi based rigs by moving Edison references to the Explorer If/Then section of the setup.  Also edited openaps-install.sh to add a user check for user edison before attempting to adduser edison to sudo and dialout groups.  Please take a close look at this as this is my first attempt at modifying code and using the Github workflow.
> Move Edison refs to Explorer IF/Then section

- bin/oref0-pump-loop.sh
Lots of people mess up their json syntax and then get cryptic errors that don't make it obvious that's what they've done.  This adds an explicit `jq .` check of preferences.json if the loop fails, and prints a clearer error message if so.
Is this clear enough?
```
ValueError: No JSON object could be decoded
supermicrobolus pump-loop failed. pump_loop_completed more than 15m old; waiting for 40s silence before mmtuning
Radio ok. Listening: ...............................................................................................No interfering pump comms detected from other rigs (this is a good thing!)
Listening for 40s silence before mmtuning: .No interfering pump comms detected from other rigs (this is a good thing!)
mmtune: "916.636", 5, -72 waiting for 24 second silence before …
```
> check preferences.json is valid json

- bin/oref0-ns-loop.sh
This includes various optimizations to make oref0-ns-loop run faster, particularly for Pi0 rigs.  It also causes it to skip non-essential ns-loop functions (everything other than getting new BG data) if system load is too high, to ensure that oref0-pump-loop can run.
> Optimize oref0-ns-loop.sh

- bin/oref0-pump-loop.sh
- lib/determine-basal/determine-basal.js
Now that we have a mechanism to retry SMBs when we are Waiting to microbolus again, we can allow SMBs a little less frequently, to reduce the chance of getting two SMBs based on the same BG data (and potentially delivering the full insulinReq, not just half of it).
> Only SMB every 3m; retry up to 2m

- lib/determine-basal/determine-basal.js
Now that eSMB allows maxSMBBasalMinutes > 30, and ZTpredBGs do a better job of preventing excess insulinReq from UAM unless there's enough carbs or time to zero temp to prevent a low, it should now be safe to allow the use of SMB on smaller basals.  The main change required to support that is that we need to round down all SMB amounts, such that (when in insulinReq/2 mode) a 0.1U SMB is not given until insulinReq reaches 0.2U, and 0.2U requires 0.4U, etc.  (Previously, a 0.11U insulinReq would generate a 0.06U SMB suggestion, which would be rounded to the nearest 0.1U.  Now, that will be rounded down to zero.)
All the same "please be careful and test everything thoroughly" caveats for SMB and eSMB still apply, but there should no longer be any technical limitation on how small basals can …
> round insulinReq down to safely allow eSMB on small basals

- bin/oref0-setup.sh
Among other things, this should make sure that rigs get updated to protect against the Krack attack on WPA2 (wifi encryption).
> make sure all apt-get packages are up to date

- lib/determine-basal/cob.js
- lib/determine-basal/determine-basal.js
When SMB'ing for very large meals of 120g (the maximum COB oref0 allows by default before capping it), we've seen low BG situations with lots of COB, presumably because insulin activity is so high that the liver starts storing all the incoming carbs as glycogen.  In order to help mitigate this, we want to prevent oref0 from assuming that very high current deviations will continue.  This change caps the maximum projected deviations at a rate equivalent to 30g/h for purposes of calculating COBpredBGs.  The slightly lower projected deviations slightly reduce how much it SMBs up front, and instead causes it to predict the carbs to hit a bit later on.  This does not affect UAMpredBGs, so they can start out rising faster than COBpredBGs, but are limited to 3h of total impact, so end up lower in …
> Limit carb impact predictions to 30g/h

- lib/determine-basal/determine-basal.js
When hot-swapping a sensor and looping off raw data, there is a very large initial jump in the reported raw BG value, which then quickly comes down and levels out at whatever level the new sensor is reading.  The current SMB safety check disallows SMBs on the initial jump, but allows them on subsequent readings (if IOB is low enough to warrant dosing off the high value despite the downtick).  To prevent SMBing off a falsely high reading, this change disallows SMBs if any of the delta, short_avgdelta, or long_avgdelta is > 20% of the current BG.
> disable SMB if either avgDelta is >20%

- lib/determine-basal/autosens.js
Last night we saw an example of a site change followed by lots of positive deviations (likely meal-related, but not all excluded as such) that caused autosens to detect its maximum allowed resistance, and subsequently caused oref0 to be a bit too aggressive with SMB.  This change makes autosens pad up to 6 additional zero deviations after a site change, so it'd be less likely to detect resistance based on too-little data.
> pad up to 90m of zero deviations after site change

- bin/oref0-setup.sh
In order to reduce confusion around people thinking that "no pump comms detected" is an error (rather than a good thing), I'd like to do a mmeowlink release and then upgrade everyone to mmeowlink v0.11.1  when they next run oref0-setup.
https://github.com/oskarpearson/mmeowlink/pull/63 needs to be merged (and released for `pip`) before this PR should be merged.
> upgrade to mmeowlink v0.11.1 for clearer pump comms messaging

- bin/oref0-ns-loop.sh
oref0-ns-loop was failing to format_ns_status on non-Edison rigs because edison-battery.json doesn't exist.  This changes it to only try to include that if it exists.
> only use monitor/edison-battery.json if it exists

- bin/oref0-setup.sh
PR #622 introduced a syntax error (bash if comparisons require square brackets) and failed to match when run non-interactively via oref0-runagain.  This changes the conditional to just match on spidev5.1 as we do elsewhere to indicate that we're on an Edison + Explorer Block rig.  cc @jsmurray1
> match on spidev5.1 to indicate explorer (for runagain); fix if syntax

- bin/oref0-pump-loop.sh
Sometimes `get-settings` fails to refresh something from the pump, resulting in a bad/empty iob.json or profile.json.  Rather than letting the loop fail and waiting for it to refresh naturally, this does so before trying to use it.
This also refactors the `openaps get-settings` alias into a function in oref0-pump-loop for better logging, efficiency, and to make things easier to tweak in the future.
> check validity of iob.json and profile.json and refresh if invalid

- bin/oref0-ns-loop.sh
- bin/oref0-setup.sh
- lib/oref0-setup/edisonbattery.json
When I removed the edisonbattery import, that broke MDT (and xDrip) CGM users who still need the old `openaps ns-loop` for now until we update oref0-ns-loop.sh to support them.
This restores edisonbattery upload functionality for MDT, and restores that plus ns-loop functionality for xDrip.
> Fix edisonbattery for MDT and xDrip.

- bin/oref0-meal.js
- bin/oref0-ns-loop.sh
- lib/determine-basal/determine-basal.js
When there is less than 3h worth of glucose data available, oref0-meal can't calculate COB, so returns zero.  However, if UAM is enabled, it also fails to return UAM information, which was propagating through to undefined / NaN for eventualBG in that situation (basically turning oref0 into just a predictive low glucose suspend system). 
This change only sets COB to zero when insufficient glucose data is available, but still calculates the UAM data if it can.  It also adds an undefined check to prevent missing UAMpredBGs from causing an undefined/NaN eventualBG.  And it adds a check to the 24h glucose refresh to force it to retry every run until it gets enough glucose data to calculate COB.
This also includes various optimizations from #741 to make oref0-ns-loop run faster, particularly …
> Calculate UAM and eventualBG when insufficient data for COB

- bin/oref0-pump-loop.sh
To reduce the risk of A52 errors, @mgranberryto resurrected the idea in https://github.com/openaps/oref0/pull/749#issuecomment-339441573 of having OpenAPS send ESC key presses before issuing SMBs.  This does so, three times, to make sure the pump is out of the pump Bolus Wizard before SMB'ing.  That will force the user to go back into the bolus wizard after the SMB completes, when it is again safe to do so.  This might also help with accidentally leaving the pump in the fixed prime screen after a rewind, but that will need to be tested.
>  press ESC three times on the pump to exit Bolus Wizard before SMBing

- bin/oref0-pump-loop.sh
When pump is suspended, the rig currently treats that as a failure and mmtunes unnecessary when pump comms are fine.  This changes that behavior to continue to refresh profile, pumphistory, etc. instead of failing out if the pump is suspended.
> don't treat suspended pump as a complete failure

- lib/profile/index.js
Everyone who's noticed any difference with exponential curves has reported it as an improvement, so I think it's best to go ahead and change the default curve from bilinear to rapid-acting before we release 0.6.0.
> change default curve to rapid-acting

- lib/determine-basal/autosens.js
- lib/determine-basal/determine-basal.js
- lib/iob/history.js
- lib/profile/index.js
Currently autosens_adjust_targets is false by default, as autosens now adjusts the basals used in calculating IOB, eliminating the need to adjust targets to compensate for IOB previously not reflecting sensitivity.  However, there are still cases where autosens doesn't react strongly enough, such as for persistent low BG due to sensitivity.  To help address that, this splits autosens_adjust_targets into two preferences: sensitivity_raises_target (true by default) and resistance_lowers_target (false by default).  As before, temp targets override any autosens-based target adjustments.
Additionally, some people find that 80 mg/dL temp targets are insufficient to bring BG down when they're running resistant, so this adds a low_temptarget_lowers_sensitivity preference (false by default) to …
> Sensitivity and targets

- lib/bolus.js
This is useful when multiple small micro boluses are being
administered. The notes will be visible in the pushover notifications from
nightscout.
> Add a note with the latest calculated IOB after boluses.

- bin/oref0-autotune-recommends-report.sh
The way oref0-autotune-recommends-report currently builds its time_list array of H:M in 30 minute increments to mirror pump basal schedule doesn't work on the day that DST ends and the clock falls back: it goes into an infinite loop from 1am to 1:30am and back instead of proceeding to 2am.
This builds that array much more simply without using `date`,with two nested `for` loops instead, to bypass that problem.
> Fix oref0-autotune-recommends-report for DST

- bin/oref0-autotune.sh
Per #736, the current "Warning: API_SECRET is not set when calling oref0-autotune.sh" message is confusing, as it only needs to be set if someone has locked down read-only access to their NS using token auth.  This PR moves the warning line to only display if autotune fails, and to clarify that the warning is only a problem if you have locked down read-only access to your NS.
> only display API_SECRET not set warning if autotune fails

- lib/determine-basal/determine-basal.js
Up until now, minGuardBG < threshold has always set 30m zero temps, even when more than 30m of zero temping would be required to bring BG back up to target.  This sets longer zero temps (30-120m) as needed in those situations.
I also realized that since we added minGuardBG, low glucose suspend mode can only be triggered if BG < threshold but BG is predicted to be >= threshold in 5 minutes.  Rather than continue to special-case that corner case, I set minGuardBG = bg initially (so minGuardBG should always be <= bg), and consolidated the old bg < threshold code into the minGuardBG < threshold case.
> set >30m zero temps when needed for low minGuardBG

- lib/determine-basal/determine-basal.js
When SMB mode is active, zero temps are set based on naiveEventualBG, and actual insulin requirements are normally covered by SMBs.  However, as per #785, there are situations, particularly with tiny basals, where insulinReq is positive, but is not high enough (0.2U) to trigger the minimum SMB of 0.1U.  In those situations, extended zero temping can occur before insulinReq gets high enough to trigger an SMB.
This PR skips the SMB zero-temp when insulinReq > 0 but microBolus < 0.1, and instead falls through to setting temp basals normally.  This should also help avoid zero temping without SMBs in cases where maxSMBBasalMinutes is too low and maxBolus < 0.1.
(This is somewhat similar to the old SMB bolus snooze behavior, which checked for `snoozeBG > target_bg && lastCOBpredBG > target_bg` …
> don't SMB zero temp if insulinReq > 0 but too low for a microBolus

- lib/determine-basal/autosens.js
Per https://gitter.im/nightscout/intend-to-bolus?at=5a08a2a471ad3f8736d66aa4 we should probably only be adding extra negative deviation if a high temptarget is running if exercise_mode or high_temptarget_raises_sensitivity is set.
> only add extra negative deviations if exercise mode is set

- bin/oref0-autotune.sh
- bin/oref0-setup.sh
When COB > 0 at midnight, it messes up autotuning of CR and post-midnight basals.  Since most people's schedules mean COB=0 at 4am a lot more often than at midnight, this PR changes autotune to run 4am-4am instead of midnight-midnight to mostly avoid those issues.
Anyone installing this branch will need to re-run oref0-setup and answer Y to deleting their old cron (or manually update the autotune cron line from 12:05am to 4:05am) or their autotune will stop tuning midnight-4am basals until they do so.
> run autotune 4am-4am instead of midnight-midnight

- bin/oref0-autotune.sh
Without intervention, the autotune/ directory can grow indefinitely, as it keeps all old entries, treatments, and autotune log files.  To reduce the disk space impact of doing so, this PR gzips all of those old files before each run.
> gzip old autotune json and log files to save space

- bin/oref0-determine-basal.js
- lib/determine-basal/determine-basal.js
- lib/glucose-get-last.js
Per https://github.com/openaps/oref0/issues/788 it would be better to cancel/shorten long zero temps when the rig stops receiving CGM data.  It would also make sense to do the same thing for CGM errors as for no data, as they're often the same condition, just with/without the CGM plugged in.  In the event of >10m old CGM data, or CGM errors, this PR will:
Cancel high temps:
{"rate":0,"duration":0,"temp":"absolute","deliverAt":"2017-11-14T01:11:00.349Z","reason":"If current system time Mon Nov 13 2017 17:11:00 GMT-0800 (PST) is correct, then BG data is too old. The last BG data was read 12m ago at Mon Nov 13 2017 16:59:00 GMT-0800 (PST). Canceling high temp basal of 3.3"}
Shorten long zero temps to 30m:
{"rate":0,"duration":30,"temp":"absolute","deliverAt":"2017-11-14T01:11:42.771Z","reason …
> Cancel high temps and shorten long zero temps when we lose CGM data

- bin/oref0-online.sh
- bin/oref0-setup.sh
Our rigs occasionally experience a kernel bug panic after attempting to renew DHCP on bnep0, usually in flight, and have to be rebooted. This limits dhclient attempts to only occur when bt-pan runs successfully.
> only try to get bnep0 IP if bt-pan succeeds

- bin/oref0-pump-loop.sh
oref0-pump-loop was saying `No smb_enact needed.` when oref0-determine-basal tried to shorten a temp.  This PR changes it to make sure that the running temp is no more than 20 minutes longer than the suggested one.
> actually shorten zero temps

- bin/oref0-pump-loop.sh
This fixes some error checks that made for ugly repeats of `ERROR: bad basal schedule [ { i: 0, start: '00:00:00', rate: 0, minutes: 0 } ]` if a bad basal schedule refresh resulted in a 0 basal profile.  With this fix, the old valid basal profile should continue to be used if the one is invalid.
> fix basal schedule error checking

- lib/determine-basal/determine-basal.js
Per https://gitter.im/nightscout/intend-to-bolus?at=5a15a1a2df09362e673ea448 @alimhassam discovered that setting a preference to the string `"false"` (instead of the boolean `false`) evaluates as `true`, which unexpectedly gave him enabledSMB_always behavior.  This PR looks for a boolean `true` (not just something that evaluates to true) for the enableSMB preferences to make things behave as you'd intuitively expect.
There may be other boolean preferences that need this treatment as well, but the enableSMB ones are the most important.
> require boolean true on enableSMB preferences

- bin/oref0-version.sh
A few changes to make the message at the end of the loop more useful if you're not running on the main `openaps/oref0 repo`.
- Check OREF0_SRC env for source code location.
- Check for being behind upstream (if it exists).
- Only warn if repo is ahead of local (not local ahead of remote)
> Make oref0-version more useful if you're not running on openaps/oref0 directly

- bin/oref0-ns-loop.sh
- bin/oref0-setup.sh
got rid of all MDT aliases and moved the uploading of the MDT CGM reading to oref0-ns-loop.
We waste less time on uploading the cgm data when there is nothing to upload yet, so since the upload loop runs faster you will have less time of a new cgm data that was received sitting around waiting to be uploaded. so it might be a bit faster on updating. 
note this does not fix the issue of collecting cgm data, just the uploading it to nightscout.
> add MDT to oref0-ns-loop

- bin/oref0-pump-loop.sh
I took another stab at adding a verbose logging or debug option to oref0-pump-loop.sh if the approach is acceptable it could be done to other scripts such as ns-loop, i got tired of changing some of these manually every time, I hope it's done in a useful way, in this case the existing behavior is not changed unless an environment variable is passed.
> Improve the oref0-pump-loop debuging options by adding a debug flag.

- bin/oref0-autotune-prep.js
- lib/autotune-prep/categorize.js
- lib/autotune-prep/index.js
- lib/autotune/index.js
When running autotune retrospectively against NS data containing many/long periods without temp basals (i.e. data from AndroidAPS, OpenAPS with profile.skip_neutral_temps = true, Loop with wide BG target ranges, or long periods without any closed looping), autotune would assume that the autotuned basals were in effect any time there was no temp basal.  That could result in a feedback loop where autotune continued trying to raise or lower basals indefinitely until it hit the autosens_max or autosens_min, rather than converging on a sensible basal schedule.  This PR changes autotune to assume that the basal schedule from pumpprofile.json was in effect instead.  That should ensure that autotune converges, and as long as the pumpprofile.json basal schedule matches what was actually in effect …
> use pumpbasalprofile for autotune IOB calculations

- www/regenerate-index.sh
- www/setup-http.sh
regenerate-index.sh creates a new file index.html every time it is run. This contains simple html formatting with example data for now (intent is to add additional parameter-value pairs for display after approval of proof of concept).
setup-http.sh is intended to be called from oref0-setup.sh and adds cron entries to start SimpleHTTPServer at reboot and run regenerate-index.sh periodically. Both files should be in ~/myopenaps/enact directory. From a browser on any device, browse to http://[RIG_IP_ADDRESS]/index.html and the page will self-refresh periodically.
> Simple Remote Access Scripts Test

- lib/determine-basal/cob.js
When BG is rising fast and then slows its rise, it currently takes ~45m for UAM to pick itself up off the floor and predict continued rise.  This shortens the UAM lookback to ~30m to make it more responsive.
> only calculate UAM deviations for the last ~30m

- bin/oref0-setup.sh
Script currently saves 'bg_targets_raw.json' as 'bg_targets_raw.json,'
Remove the errant comma at the end of the output file name.
> Fix typo in setup script for 512 files

- lib/determine-basal/determine-basal.js
Now that enableUAM is on by default, we should probably make use of it in non-SMB contexts as well, to help AMA determine when high-temping is needed due to undercounted carbs, etc.
> don't require enableSMB to enableUAM

- lib/iob/history.js
Due to the way temp basal splitting works, the temp basal verification safety checks sometimes erroneously determine that a running temp basal doesn't match what's in pumphistory.  This PR continues to make use of the splitHistory internally, but returns the un-split tempHistory records for use in verification checks.
> only use splitHistory internally: return un-split tempHistory

- bin/oref0-pump-loop.sh
- bin/oref0-setup.sh
Since we removed the edisonbattery.json import for non-MDT and non-xDrip users, newly installed rigs may not properly refresh the monitor/edison-battery.json file or properly check for low voltage to shut down the rig if oref0-ns-loop can't talk to NS and ns_meal_carbs fails.  This PR fixes oref0-pump-loop and crontab to not rely on the alias.
> fix Edison batteryVoltage

- lib/determine-basal/determine-basal.js
Per https://github.com/openaps/oref0/issues/781 and other feedback, and my own experience, it seems that 120m SMB zero temps may be doing more harm than good.
This PR caps SMB zero temps to 60m, while allowing zero temps based on minGuardBG or eventualBG to still extend to 120 minutes.  This should minimize the situations in which really long zero temps are set where unneeded, while preserving the ability to set them when BG predictions actually justify.
> limit SMB zero temps to 60m

- bin/oref0-pump-loop.sh
- lib/basal-set-temp.js
- lib/determine-basal/determine-basal.js
Per #840, skip_netural_temps currently breaks the temp basal safety checks, because the neutral temp we attempt to set to fix the situation never gets set.
This PR fixes that by issuing a cancel temp when the safety checks fail, and making sure that such a cancel temp command actually gets passed through to the pump.
This also includes a new feature to cancel temp basals (unless they're low glucose suspend zero-temps) after 55 minutes past the hour if skip_neutral_temps is set, so that no temp basal will be running at the top of the hour and therefore the pump will not beep or vibrate.
> Cancel temp on error and > 55m w/ skip_netural_temps

- bin/ns-get.sh
When tokenauth was added, an improperly escaped CURL_AUTH= line was also added.  It hasn't done much harm, since anyone not using tokenauth has their NS site world-readable, but in @kandhoff's case (running autotune on a Mac) it seems to be breaking something: https://gitter.im/openaps/autotune?at=5a1e307c540c78242d5f36c3
This PR simply comments out the non-functional line to see if that helps.
> comment out broken CURL_AUTH API_SECRET line

- bin/oref0-setup.sh
Now that oref0-pump-loop is no longer using `openaps report invoke enact/suggested.json`, disabling autosens in oref0-setup doesn't actually disable its use, just prevents it from being updated, which can result in the sensitivityRatio getting "stuck" on whatever the last value was when it was disabled.
To simplify everything, this PR removes the interview question about autosens and always enables the autosens-loop.  If someone really needs to prevent autosens adjustments while they troubleshoot an issue, they can set their autosens_min and autosens_max in preferences.json to 1.
> always enable autosens-loop

- bin/oref0-mdt-trend.js
It seems that there are occasionally records from MDT cgm with a sgv of 0. This causes the trend arrows to think that BG is rising rapdily. 
Written without my rig nearby (oops), so needs to be tested by me or another MDT CGM user before merge.
> Ignore records with 0 sgv

- lib/determine-basal/autosens.js
It can be difficult to evaluate whether changes to less-intuitive settings changes like insulin peak time/DIA are likely to be helpful.  By calculating RMS deviation in autosens we have a metric measuring how well the current settings are predicting observed values.  
A change reducing RMS error will likely improve results and a change increasing RMS error will likely be unhelpful.
> Display RMS deviation in autosens

- lib/autotune-prep/categorize.js
The current UAM-exclusion algorithm in autotune is based solely on IOB being higher than 1h of basal.  This, however, tends to miss cases where BG starts rising rapidly (perhaps from rescue carbs) with no IOB covering it.  To avoid raising basals in such a situation (and requiring even more rescue carbs later), this adds a UAM exclusion for any deviations > 6 mg/dL/5m.
When too much data is excluded as UAM, autotune adds back in the UAM deviations to avoid getting stuck in a bad equilibrium of too-low basals that prevent it from ever tuning them higher.  However, as implemented in 0.6.0, this sometimes results in autotune raising basals too high, and the addition of the 6 mg/dL/5m exclusion would make that more common.  To avoid both problems, this PR also makes autotune only include the …
> Autotune: avoid raising basals from UAM

- bin/oref0-bluetoothup.sh
- bin/oref0-setup.sh
- bugfix: also start bluetoothd in oref0-bluetoothup if it's not running
- upgrade bluez to 5.48, changelog http://www.bluez.org/release-of-bluez-5-48/
- remove `--experimental` (finally) on bluetoothd startup and change it in /etc/rc.local if it's still there
Tested with pebble and works. Will test bluetooth tethering later on.
> Upgrade bluez to 5.48, start bluetoothd if it's not running, remove experimental

- logrotate.rsyslog
Recently, several users have reported problems due to missing disk space on their rigs.  With the current configuration, log files can easily consume several hundred megabytes.
This small change lets the rig delete non-OpenAPS logs (system, cron, etc.) much earlier. I have been using this configuration for a while and it has kept the size of my non-OpenAPS log files below 100MB.
This PR does not touch the treatment of OpenAPS log files.
> Delete non-OpenAPS log files earlier to save disk space

- bin/oref0-pump-loop.sh
This PR adds the ability to measure how much time it takes for each portion of the oref0-pump-loop to run, and writes the results to /tmp/timefile.txt.  This has proven quite useful in figuring out how to speed things up, so rather than maintain it as a separate branch, I'd like to merge it into dev.
> Add profiling support

- bin/oref0-setup.sh
Starting oref0-pump-loop after a 30s sleep as well as at the top of every minute works great, but it also causes oref0-pump-loop to start up again even after a `sudo service cron stop; killall oref0-pump-loop` if it's performed while the sleep is active.  To reduce troubleshooting confusion, this PR reverts the addition of the sleep 30 line in crontab.
> don't start oref0-pump-loop every 30s

- lib/autotune/index.js
The test for autotune ISF adjustment fraction from the profile test to see if it is true. This has the unintended consequence of setting the adjustment fraction to 1 when the profile setting is 0.
This modification changes the test from a test of whether its value is true to whether it exists.
> Fix autotune ISF adjustment fraction

- bin/oref0-pump-loop.sh
When settings/bg_targets_raw.json got moved into NON_X12_ITEMS, it caused settings/bg_targets.json to be run before settings/bg_targets_raw.json, which caused it to fail on a new install unless the settings/bg_targets_raw.json was created manually.  This moves settings/bg_targets.json into NON_X12_ITEMS as well, so it gets run after settings/bg_targets_raw.json.
We'll need to make sure this still works will x12 pumps (that they don't need us to run the settings/bg_targets.json report).
> Fix profile bootstrapping

- bin/oref0-pump-loop.sh
- bin/oref0-setup.sh
This work in progress branch replaces the use of the `openaps` toolkit and `mmeowlink` with @ecc1's Go-based tool for talking to `medtronic` pumps (https://github.com/ecc1/medtronic).  It promises to work much faster than `openaps`, allowing better battery life on Raspberry Pi based rigs, but still requires extensive testing.
> Go-based replacement for openaps toolkit for use with Explorer HAT

- bin/oref0-autotune-prep.js
- bin/oref0-autotune.sh
- lib/autotune-prep/categorize.js
- lib/autotune-prep/index.js
This adds an option to autotune for a user to manually add a --categorize-uam-as-basal option to the command line to add all UAM categorizes BG data to basal data. This is useful if the user is confident all carb intake events were logged and the user's basal rates are far enough from reality that time periods are being incorrectly categorized as UAM events instead of basal events.
> Autotune Command Line Option to Classify UAM as Basal

- lib/autotune/index.js
When the database has mixed dateStrings containing zulu time lib/autotune/index.js would pick the wrong hour value when looking at the deviations per hour. This uses the Date object with the same methods as used in categorize arrive at the correct local time hour.
> Fix Autotune TZ Issue

- bin/nightscout.sh
The G5 transmitter with xdrip-js can regularly have time gaps slightly greater than 5 minutes. Opening the window to identify gaps from 5 minutes to 6 minutes prevents generation of the false gaps.
> Open lsgaps Entry Gap Window

- bin/oref0-pump-loop.sh
When oref0-determine-basal generates an error and doesn't generate a full recommendation, oref0 0.6.0 currently doesn't display that.  This PR does an explicit check for the deliverAt field in the smb-suggested.json, and prints the contents before exiting if it's not found.
> print enact/smb-suggested.json if deliverAt check fails

- lib/determine-basal/autosens.js
We sometimes see BG running low overnight due to resistance detected during the previous day.  To prevent that, this PR forces autosens to reduce positive deviations to zero any time BG is less than 80 mg/dL, which quickly decays away any previously detected resistance, and prevents autosens from detecting further resistance as easily if BG has been < 80 for very long during the last 8h or 24h.  It will *not* cause autosens to detect sensitivity any more than it otherwise would.
Here's an example of autosens output from before this change:
```
Calculating sensitivity using 8h of non-exluded data
+60g(xxxxxxxx22h=xxxxxxxxxxxx23hxxxxxxxxxxxx0h=x)-++++++++++1h-+++--+++-++2h=-+-++++++++-3h-+-++---++++4h=++++----+-++5h+++--+++++++6h=+++-------+-+-7h+-------+-+-+-+-+-+-+-+-8h=+-------+---+-----+ …
```
> Autosens: don't detect resistance based on + deviations with BG < 80

- lib/autotune-prep/categorize.js
As with #902, we sometimes see autotune tuning/leaving basal too high at a time of day when BG is low.  To prevent that, this PR forces autotune to reduce positive deviations to zero any time BG is less than 80 mg/dL.  This in turn causes it to lower basals, raise ISF, or raise CR when BG is too low for too long.
> Autotune: don't detect resistance based on + deviations with BG < 80

- lib/iob/calculate.js
- lib/iob/total.js
- tests/iob.test.js
The IOB calculation was forcing a minimum of 5 hour DIA by calculate.js; however, the total.js script was only using the history up to the user's pump profile DIA setting, not the full 5 hours if their pump was set to less than 5 hour DIA.
This change makes total.js and calculate.js force a 5 hour minimum consistently.
> Fix iob calculation error

- bin/oref0-pump-loop.sh
settings/bg_targets.json is generated from settings/bg_targets_raw.json, adding the user-preferred units, and pulls no data from the pump.
> Generate settings/bg_targets.json for x12 models

- bin/oref0-setup.sh
This will allow locale checks in other parts of openAPS to determine which locale (US or WW) the radio is using.
> Store radio_locale in pump.ini

- bin/oref0-autosens-history.js
- lib/determine-basal/autosens.js
This is a tool for calculating autosens retrospectively, which will be useful in processing data uploaded to the OpenAPS Data Commons.  Merging it into go-explorer-hat for testing to make sure none of the changes to lib/determine-basal/autosens.js cause any issues.
> autosens-history

- bin/oref0-pump-loop.sh
Fix issue where pumphistory exit code wasn't causing the if statement to fail, and loop was continuing with a stale histroy file
> Fix pumphistory exit code ignored.

- lib/determine-basal/determine-basal.js
- tests/determine-basal.test.js
Per discussion starting at https://gitter.im/nightscout/intend-to-bolus?at=5a991c2ff3f6d24c6829961b, @jane49 had an issue where her xDrip+ app repeatedly and indefinitely reported the last meter BG as the SGV/glucose value until she calibrated again.  This is a serious safety issue, as a high calibration before bed could result in OpenAPS continuing to dose extra insulin all night without knowing that BG is actually dropping, potentially leading to severe hypoglycemia or worse.
This change prevents oref0 from looping on "stuck" CGM data by requiring that either short_avgdelta or long_avgdelta be non-zero.  This might also prevent it from looping on the first data point after a long CGM gap, which is probably also a good thing.
I've tested this against the problematic glucose.json …
> Don't loop on "stuck" CGM data

- lib/oref0-setup/bg_targets_raw.json
- lib/profile/isf.js
- tests/profile.test.js
Since only `offset` is used in calculating which isf is effective for the given
`timestamp`, these other fields add unnecessary confusion to the profile data.
Removing them here allows future removal in decocare and other profile.json
sources. Cleaner (and less) code, cleaner data, easier mental model :)
> Remove i, x, and start from isf guard check

- bin/oref0-setup.sh
- Give the option to download the go precompiled binaries  …
instead of recompiling and installing all the extra go stuff.
This requires precompiled binaries to be released, but it's an
improvement specially on the pizero where the setup is so long otherwise.
- Run apt-get clean at the end of setup
> Go precompiled setup

- lib/meal/history.js
- tests/cobhistory.test.js
trying to match bolus wizard entries to corresponding
bolus entries.
This allows out of order bolus and bolus wizard entries to
still work correctly.
Before this change, when the bolus entry was after the bolusWizard
entry, the carb was being skipped because no corresponding
bolus was seen.
I'm hoping this will help with the issue reported in #952
> Slightly refactor oref0 meal to read all the data before

- bin/oref0-pump-loop.sh
jq --exit-status always returns a 0 exit code when the
input is empty. This breaks a couple of usage.
Verify that the file exists and is not empty first.
Also remove unnecessary calls to cat, jq could take the input
file as an argument.
> fix jq -e usage with empty files.

- bin/oref0-pump-loop.sh
added two if statements to supress mmtune execution if carelink stick is used. 
Users have to add the "line radio_type = carelink" to pump.ini file.
Modification is tested by d3xr and myself.
> backport carelink support by supressing mmtune execution

- bin/oref0-setup.sh
pr #752 reverted the change where xdrip cgm users were moved back to use the
openaps ns loop. This doesn't seem needed anymore, and has been working for me for couple of weeks.
> move xdrip cgm to oref0-ns-loop

- lib/iob/history.js
- lib/iob/index.js
- tests/iob.test.js
A couple of places in the IOB library used the current clock time instead of the time provided by the inputs. This PR changes those places to use the input clock and updates the tests iob module to account for the change.
> Use Current Time Input Consistently in IOB Lib

- bin/oref0-setup.sh
The frequency of log-file rotation is controlled by config files, but
also by when logrotate is run by cron. Log-rotation is important to
prevent running out of disk space; since the log files are extremely
compressible, but can grow quickly, a day or two's worth of logs can
potentially deplete the disk space on an Intel Edison, causing problems.
Past commits tried to address this by changing the log-rotation schedule
in logrotate's config files, but it didn't work because the process that
*reads* the config files still only ran once per day. This changes that
from daily to hourly.
> Make logrotate in cron run hourly instead of daily

- bin/oref0-setup.sh
Will ensure openaps.jq will be updated when the medtronic repository is updated.
> Symlink instead of copy openaps.jq

- bin/oref0-autosens-loop.sh
Fix a typo that would cause completed_recently in oref0-autosens-loop.sh to always be false. This effectively disabled a feature that was supposed to make autosens recalculation happen less frequently when under high load.
> Fix typo in filename of /tmp/autosens-completed

- bin/oref0-setup.sh
Different location this time. Not sure why it wasn't using -q in the first place, either?
> Don't error when HAT file doesn't exist

- lib/determine-basal/determine-basal.js
- lib/profile/index.js
Currently, SMB is limited to delivering 30m worth of basal at a time unless IOB is insufficient to cover COB (generally after meal carbs have been entered, but only a partial bolus or no manual bolus has been given).  Some people have found it necessary to make SMB more aggressive even in the absence of meal announcements, so this provides an optional preference to control SMB's maximum bolus in the UAM case similarly to how maxSMBBasalMinutes controls it in the announced-meal case.
Special thanks to @dcacklam for identifying this as a problem and testing a similar fix.
> make maxUAMSMBBasalMinutes a preference

- bin/oref0-online.sh
When my phone is in and out of service several times in as many minutes (between subway stations, for example) it doesn't assign an IP address to the device when it tries to connect via Bluetooth. Once back in a more stable environment it takes a while before it tries to get on the Internet via Bluetooth again. This change, tested over several weeks, significantly reduces the time offline during and after using the subway.
> Try three times to get a Bluetooth IP address

- bin/oref0-set-device-clocks.sh
Stop trying to set-device-clocks for CGM on xdripaps installs.
When this command is executed, it results in a loop failure due to 'failure' to set the pump clock, when in reality the pump clock was set, but the non-existent xdripaps CGM clock was not.
While this is normally 'OK' on the next loop, it is somewhat inefficient to have to redo the entire loop because a command that shouldn't have been executed, was executed. 
Fixed by looking for the xdrip.ini file & skipping the CGM clock update if it is found.
> Trying to update the 'clock' on xdripaps causes an un-needed loop fail

- bin/oref0-pump-loop.sh
More reliable check for x12 models, and skips trying to get status from x12 pumps as they do not support that command.
> x12 support in 0.7.0

- bin/oref0-setup.sh
After the 4/18/2018 release of Raspbian the kernel version is >4.10, but we still need MRAA installed.
> Fix MRAA installation on newer RPi kernels

- bin/oref0-setup.sh
Add carelink to pump.ini automatically for carelink installs instead of forcing people to manually add it.
> Add carelink to pump.ini automatically for carelink installs

- lib/iob/history.js
Using the profile_data.current_basal rather than the basal rate for the time of the insulin delivery event creates a scenario where the basal rate used for all of the insulin delivery events is only the current rate rather than the scheduled rate.
> Fixed currentRate calculation when using autosens.

- bin/oref0-pump-loop.sh
This update adds a function to enable an optional duty cycle check, to slow down the loop execution.
The intention is two fold: 
First the battery consumtion is reduced drastically (Pump and Pi)  if the loop runs less often.
Second if carelink is used, the loop produces to much communication, 
pretty much killing the communication between the pump and enlite sensors.
In default configuration this feature is off (DUTY_CYCLE=0) and doesn't change the loop execution.
> adding duty cycle feature for carelink + mdt users

- lib/profile/index.js
now that xDrip+ communicates noise information, it should be safe to enableSMB with.
> update xDrip+ enableSMB warnings

- lib/determine-basal/determine-basal.js
- lib/profile/index.js
The current cutoff for activating exercise_mode / high_temptarget_raises_sensitivity is > 110 ( >= 111 ).  This seems to cause confusion over the behavior of temp targets in the 101-110 range.  To simplify things, this PR proposes removing the + 10 threshold, so that exercise_mode / high_temptarget_raises_sensitivity apply proportionally to any temp target > 100 ( >= 101 ).
> activate exercise_mode / high_temptarget_raises_sensitivity at 101

- lib/autotune-prep/index.js
- lib/autotune/index.js
Rather that just comparing the square of deviations, this PR modifies the insulinPeakTime and insulinEndTime tuning to use both the Root-Mean-Square Error/Deviation (RMSE) and Mean Absolute Error (MAE), and only adjusts peak/end time if both RMSE and MAE are in agreement as to which direction to tune.
Background on RMSE and MAE: https://medium.com/human-in-a-machine-world/mae-and-rmse-which-metric-is-better-e60ac3bde13d
RMSE is referred to in the code as RMSDeviation, and MAE as meanDeviation, as I picked those names before I realized that the statisticians had formal names of their own already.  :-)  There's also a Square-Mean-Root value that I calculate but don't currently use, as it seems to give the same answers as MAE.
> Compare both RMSD and MAE

- bin/oref0-setup.sh
-npm or --npm_install = force will force `npm run global-install` as long as you aren't on the master branch
removed `if` statement around the download of GoLang from google because buildgofromsource shouldn't have any bearing on whether Go is downloaded... was causing issues on a fresh rig/build
#973
> Added force npm install argument and fixed dexcom go complied binaries not being downloaded

- .travis.yml
- bin/openaps-packages.sh
- bin/oref0-autotune-export-to-xlsx.py
- bin/oref0-autotune.py
- bin/oref0-dexusb-cgm-loop.py
- bin/oref0-setup.sh
- bin/oref0_autotune_export_to_xlsx.py
- tests/check-syntax.test.js
This adds a unit test which goes through the source (everything in
oref0/bin and oref0/lib) and attempts to compile/parse each Python,
Javascript and shell file, failing the test if there are syntax errors.
For Python, this is done with Python 3, regardless of whether the file
specifies Python 2 or Python 3 (currently there are some files using
each). Since Python 3 is stricter, some files were changed to pass
Python 3's stricter syntax rules, in particular, converting mixed spaces
and tabs to all spaces, and putting parentheses on print() statements.
>  Unit test to syntax-check script and source files

- bin/openaps-install.sh
Fixes an issue where openaps-install.sh cannot find packages on the pi after running a dist-upgrade.
> Re-run apt-get update after dist-upgrade

- bin/oref0-setup.sh
Stops the cron service after the user agrees to run the setup process. Not as much on the Edison, but on the Pi Zero npm slows to a crawl while the loop is running, adding nearly 10 minutes to the setup process. At the end cron is started back up in case the user chooses not to restart immediately.
> Stop cron during setup in 0.7.0-dev

- bin/openaps-install.sh
- package.json
- release-master.sh
I'm fairly confident `ntpdate` is not used and is not required, since it is [deprecated](http://support.ntp.org/bin/view/Dev/DeprecatingNtpdate), but I have not taken the time to test removing it.
The scripts for setting clocks use the ntp daemon and this PR installs it. Did a fresh install today and was required to install it manually (error about `/etc/init.d/ntp` not found.)
[oref0-set-system-clock.sh](https://github.com/openaps/oref0/blob/2be51a45950da2a68f46d72c528207e2915e934e/bin/oref0-set-system-clock.sh#L44)
[oref0-set-device-clocks.sh](https://github.com/openaps/oref0/blob/682d7f8d4f833d640cf89b9694e3c74ff9504cff/bin/oref0-set-device-clocks.sh#L44)
If someone else can validate `ntpdate` can be deleted, I can change that as well.
> Install ntp daemon as used to set system and device clocks.

- lib/oref0-setup/mdt-cgm.json
Remove wrong trailing comma in mdt-cgm.json to make setup working again for MDT users.
> fix mdt-cgm.json

- bin/oref0-setup.sh
Provided the variable for the `validate_g4share_serial` to actually check... wasn't passing so g4-go loop wasn't working.
Changed `ls` commands to check for file existence to `test -f`
> Fix G4 w/ share crontab entry logic and other file existence adjustments

- tests/json-wf.sh
this adds a quick effective repo-scope JSON tester as a shell script in the `tests` directory (later leverage-able by CI)
monochrome doesn't really do it justice, but there are two files already not well-formed (...next PR), still detectable by the "4" in the line indicating the `jq` return code for not legit JSON, as well as an overall fail
```
$ tests/json-wf.sh  ; echo $?
/home/thecubic/code/oref0/lib/oref0-setup/device.json
/home/thecubic/code/oref0/lib/oref0-setup/dexcom.json
/home/thecubic/code/oref0/lib/oref0-setup/pancreoptions.json
/home/thecubic/code/oref0/lib/oref0-setup/shareble.json
/home/thecubic/code/oref0/lib/oref0-setup/supermicrobolus.json
/home/thecubic/code/oref0/lib/oref0-setup/vendor.json
/home/thecubic/code/oref0/lib/oref0-setup/basal_profile.json …
```
> JSON tester

- bin/openaps-packages.sh
The latest node-js for raspbian deprecates the use of nodejs-legacy, which breaks this script on new pi installs. This will make it so that nodejs-legacy is only installed on the edison.
> Fix nodejs-legacy breakage on latest raspbian

- lib/iob/history.js
This change lets Autotune recognize Nightscout AndroidAPS Temp Basal records. It also addresses the way AndroidAPS cancels Temp Basals (by creating a record without duration and rate).
I have tested the changes with OpenAPS data (no change) and AndroidAPS data.
It does not address the following issues:
- Some pumps used with AndroidAPS create Temp Basal entries on a percentage basis instead of absolute values
- Autotune does not use AndroidAPS profile switches but makes its recommendations based on the profile used by OpenAPS
AndroidAPS Temp Basal entry (with Combo pump)
```
{ 
"_id" : ObjectId("123456"), 
"eventType" : "Temp Basal", 
"duration" : NumberInt(15), 
"absolute" : 0.48400000000000004, 
"created_at" : "2018-01-20T02:33:56Z", 
"enteredBy" : "openaps://AndroidAPS", 
"NSCLIENT_ID" …
```
> Autotune: Properly parse AndroidAPS Temp Basal records

- bin/oref0-pump-loop.sh
wait_for_bg was waiting even though mdt was configured. Old grep command wasn't working any more and was replaced by get_pref_string function.
> fix wait_for_bg with mdt

- bin/oref0-set-device-clocks.sh
it is same clock as pump, so no clock update needed
> suppress cgm update if mdt is configured

- bin/oref0-pump-loop.sh
I removed messages when duty cycling is disabled.
>  update duty cycling code

- lib/determine-basal/determine-basal.js
- lib/profile/index.js
Current SMB logic assumes a 0.1U multiple for boluses. Different pumps support different bolus increments, so make this configurable in the profile.
I use AndroidAPS rather than OpenAPS so I might well have got the profile setup structure wrong and I don't have an OpenAPS rig to test this on, so please let me know if anything needs changing!
> Pump specific SMB size

- bin/oref0-setup.sh
Added an option to specify which version of go lib to use. This is useful for different reasons:
1. to manually enter a pre-release version, 
1. To select an older or alternate version if needed.
1. When we move to master, we could easily build upon this functionality to freeze the default version being downloaded. This will be done by changing the default value of the $ecc1medtronicversion variable from `latest` to the version we want to use on master.
Note: i just wrote the code rapidely for this, but didn't have time to test it yet as my dev rig isn't working at the moment. 
If someone can test that it all works it would be appreciated, otherwise i'll try to verify it all works once my spare rig is fixed.
cc: @ecc1
> Option to select a pre-release go lib version

- bin/oref0-pump-loop.sh
- Lowers the threshold used in `onbattery` to determine whether the device is plugged in to 90%
- Removes a call to `onbattery` that causes Nightscout to be updated closer to real-time (and removes two therefore redundant if statements)
> Reduce onbattery threshold, refresh data faster

- bin/oref0-pump-loop.sh
We've seen intermittent reports in Gitter of what looks like it might be a race condition around incremental pumphistory refreshes during bolus wizard events, which can cause the carb portion of the bolus wizard record to be recorded but not the insulin portion. This presents a safety issue, so to mitigate it this PR performs a full pumphistory refresh at the end of any loop where a bolus is delivered or a temp basal is set, and there's time before the next BG comes in and we need to start the next loop.  This should dramatically shrink the window in which a bad incremental pumphistory refresh could impact dosing decisions, without negatively impacting loop speed or reliability.
> Full pumphistory refresh after bolus/enact if no new BG yet

- lib/determine-basal/cob.js
Under certain circumstances when NS has glucose calibration records, cob.js will crash due to avgDelta being undefined.
This PR updates the logic to avoid avgDelta the error causing the crash.
> Fix cob.js Crash

- bin/oref0-pump-loop.sh
Today, our rig ended up with a zero size file for settings/basal_profile.json. The jq command doesn't return an error code if it doesn't find the value argument, so the get_settings didn't fail.
This PR checks to ensure there are valid values using grep on the output of jq.
It needs to be tested for mmol and carb ratio units other than grams.
> Pump read error checking

- bin/openaps-bootstrap.sh
- bin/openaps-install.sh
I haven't tested this, but i think it should work. 
It will allow testing `openaps-packages.sh` from a different branch and also automatically do the fresh install from a different branch than master.
> Allow specifying another branch on the command line to openaps-install

- bin/oref0-get-profile.js
- bin/oref0-pump-loop.sh
Add requirement for 4 non-hyphenated arguments in oref0-get-profile
Remove extra (and confusing) autotune argument argument for non-autotune oref-get-profile
> Fix oref0-get-profile args

- bin/oref0-pump-loop.sh
The 4 ESC seems to be done too quickly now that we moved to the go library.
It seems like it isn't as good at avoiding A52 errors as what
was done on master. I think on master the pump is wakened up again between
each key presses, or the python layer adds some latency which isn't
there on the new version.
The compromise here is to send the first ESC, wait for 0.5s before sending the
remaining ESC. From testing on a test pump, this seems to reduce the
chance of getting an A52 error.
> Split the pre-bolus ESC key presses in two commands.

- bin/oref0-pump-loop.sh
- tests/tests-in-shell.test.js
If one of the read commands fails in get_settings and leaves a file in an invalid state, the loop won't correct the problem until it determines it is time to read the profile again.  This PR will recognize the failure, and set the age of settings/profile.json and settings/settings.json to force get_settings to be called again.  This is how I recovered from the loop failure below after it occurred for more than 20 minutes.
The pump-loop.log capture below illustrates the problem this is intended to fix.  The failure is due to an empty ~/myopenaps/settings/basal_profile.json file when oref0-meal.js attempts to get the contents on line number 50.  I believe this can only happen from a failure in get_settings since I was unable to locate any other place in the software that can delete the …
> Force settings refresh on next loop if get_settings had a failure

- bin/oref0-pump-loop.sh
If pump settings read is interrupted from an event such as a kill or rig reboot, the loop will fail until profile or settings needs to be refreshed.
This validates the pump settings files contain valid content as part of the decision to call get_settings.
> Validate pump settings

- bin/oref0-pump-loop.sh
The next version of openaps-menu will use a socket server interface for external control of the display, so we don't need to call status.js if the user has the new interface script (status.sh).
> Use status.sh instead of status.js, if possible

- bin/oref0-ns-loop.sh
On slow rigs (like Raspberry Pi Zero W underclocked to 500 MHz or overheated), the loop is executed for more than 5 minutes, and the `devicestatus` is not sent to the Nightscout.
Consider `suggested.json` recent for 10 minutes.
I tested this for several days, and everything works well, 10 minutes should be enough for everyone.
> Consider suggested.json recent for 10 minutes

- bin/oref0-autotune-core.js
- bin/oref0-autotune-prep.js
- bin/oref0-autotune.sh
- tests/command-behavior.tests.sh
This is an attempt to address #1093.
Having tested Fiasp a couple of weeks ago, we noticed the same behavior.
This uses the pump profile to keep curve, dia, and peak up to date.
> Fix Stale Autotune Profile

- bin/oref0-pump-loop.sh
We just added wait_for_silence to oref0-bash-common-functions via https://github.com/openaps/oref0/pull/1081 so we can now remove it from oref0-pump-loop and use the new common one.
> use oref0-bash-common wait_for_silence in oref0-pump-loop

- bin/oref0-setup.sh
If the local go binaries are running, the copy will fail and setup will die. This PR asks the user if it's okay to kill any running binaries and then kills them if requested.
My editor also auto-fixed some inconsistent spacing; lmk if this should be undone.
> Stop local go binaries before overwriting. Fixes #1049.

- bin/oref0-bash-common-functions.sh
I noticed that a few of the usages of `prompt_yn` in `oref0-setup.sh` were feeding the function a default value of `Y`, but the `prompt_yn` only displayed correctly when given `y`. The default value would still be correct, but the text displayed to the user was wrong. I updated the conditional to allow `Y` or `y` as the default value.
> Fix default input detection in prompt_yn common function

- lib/determine-basal/determine-basal.js
Added additional falsy check for sensitivityRatio in determine-basal to mitigate subsequent use from a possibly 'undefined' value, here for remainingCATimeMin
> Added additional falsy check for sensitivityRatio

- bin/oref0-pump-loop.sh
This came up in #1022 as something to do, but merging #1140 broke setting pump time for me so I thought now would be a good time to do it 😁. If `openaps-use` is still supposed to work on dev, I'd be happy to tweak this, but it doesn't look like it is in other places in the script.
`timerun` doesn't exist anymore...
```
34069-Pump clock is more than 55s off: attempting to reset it and reload pumphistory
34070-Checking pump status (suspended/bolusing): {"status":"normal","bolusing":false,"suspended":false}
34071:/usr/local/bin/oref0-pump-loop: line 978: timerun: command not found
```
...and after removing that, the `openaps use` command fails:
```
Pump clock is more than 55s off: attempting to reset it and reload pumphistory
Checking pump status (suspended/bolusing): …
```
> fix sending escs before setting clock

- bin/oref0-setup.sh
Removes lines that edit `/etc/network/interfaces` in `oref0-setup.sh`, which cause dhcpcd to crash on the latest Raspbian. See: https://github.com/openaps/oref0/pull/1150#issuecomment-449660472
> Fix for loss of wifi issue on Raspbian

- bin/oref0-setup.sh
@scottleibrand  
Here is the re-add that shouldn't cause an issue with rpi. @cluckj would you be willing to validate this?
> Re-adding bnep0 check into oref0-setup.sh

- bin/oref0-setup.sh
Updates `oref0-setup` to check whether the `openaps` version installed is at least 0.2.2-dev and upgrading if so (https://github.com/openaps/openaps/pull/139).
> Update oref0-setup to pull openaps 0.2.2-dev for G6 receiver support

- bin/oref0-mdt-update.sh
When monitor/cgm-mm-glucosedirty.json is empy (maybe caused by filesystem damage or sudden power loss), the script will end with a "timeinterval less than 5 minutes" massage. There is no way out of this loop until the file gets deleted. I've added a check for empty file and delete the file if it is empty to force the script to a full refresh.
Testen on my pi0 based rig. The error is easy to produce with "rm monitor/cgm-mm-glucosedirty.json && touch monitor/cgm-mm-glucosedirty.json" on the old scrit. With the new script it works fine.
> hotfix mdt not syncing bug

- bin/oref0-pump-loop.sh
This creates json data in `monitor/status.json` which will bypass `smb_verify_status` for x12 model pumps.
> Bypass smb_verify_status with x12 pumps

- bin/oref0-setup.sh
Will install pi-buttons repository (standalone button interface service), depends on a commit to openaps-menu to support this new interface (https://github.com/openaps/openaps-menu/pull/22)
> Support for pi-buttons

- .travis.yml
- bin/oref0-autotune.py
Like #1189 but on the __dev__ branch instead of the master branch
> Travis CI: Add current Node.js and Python 2.7, 3.7

- .travis.yml
As discussed at https://github.com/openaps/oref0/pull/1176#issuecomment-464483637
“__node__” is currently v11.10.0
> Travis CI: Run node_js tests on "8", "10", and "node"

- lib/iob/calculate.js
`curve` not defined, evidently should be `profile.curve`, the property tested in the lines above
> Error message should refer to property tested above

- bin/nightscout.sh
I found a bug with the convert json to jq PR that prevents the latest NS treatment time from being correctly produced for the NS loop.  
This corrects the error.
> Fix latest-ns-treatment to return an object instead of array

- bin/oref0-meal.js
Error message is explicit about which data failed to process
> Explicit error messages in oref0-meal

- bin/openaps-install.sh
This will avoid having to make a choice during the apt-get update between the modified sshd_config and the one included in the update.
> Move sshd_config mod to after apt update

- bin/nightscout.sh
This fixes an oref0-setup.sh failure that was caused by the json to jq PR.
> Fix pattern match in nightscout.sh

- bin/oref0-setup.sh
Fix for https://github.com/openaps/oref0/issues/1149
> Set cgm_loop_path for plugged-in G5 receiver

- bin/oref0-pump-loop.sh
This PR adds the ability to inject custom script(s) to run synchronously at the end of every oref0-pump-loop. Any script files with executable flag set will be run as follows:
If the script file is placed in the plugins/every folder then the script runs at the end of every loop.
If the script file is placed in the plugins/once folder then the script once at the end of the current loop.
Script files placed in the plugins/once folder will be removed once run. This allows for a use case such as the following:
Logger and Lookout both call a pump utility called fakemeter that helps out users in offline mode by sending the current CGM (Dexcom) glucose value as a meter glucose value. This shows the glucose on the pump every 5 minutes and allows you to quickly see the current glucose value on the …
> ability to add script plugins to oref0-pump-loop

- bin/oref0-ns-loop.sh
This adds support for a low-battery file that contains True or False.
It's purpose is to support a low battery notification for rigs that have a low-battery discrete instead of a battery meter.
> Support Low Battery File

- bin/oref0-mmtune.sh
Bug introduced by #1176: oref0-mmtune was always starting Go-mmtune with the -ww flag; this should make the check do what it's supposed to.
> Fix check for WW pumps

- bin/oref0-setup.sh
Switched repo from colinlennon to my fork of the xDripAPS code which adds a lot of new capabilities. This has been tested by me for 2 months, without any issues. It has also been tested by a member of the openaps community - @jpcunningh.
@jpcunningh Can you please comment here to show the community you tried my release without issues?
> Switch xDripAPS to a more up to date - maintained fork release

- bin/oref0-mmtune.sh
- bin/oref0-pump-loop.sh
- Comments out code in oref0-pump-loop that doesn't do anything except show an error in the logs
- Logic of this check was inverted by #1176, this should fix it.
> Inverted logic fix for oref0-mmtune.sh, and bug fix for oref0-pump-loop.sh

- bin/oref0-setup.sh
Some jq calls between lines 683 and 1132 need `sub`, which is only supported in newer versions of jq...
> Move jq update earlier in the install script

- bin/oref0-bluetoothup.sh
This adds some log messages and provides support for various locations of the bluetoothd executable.
My Pi location from Pi Bakery image was /usr/sbin/bluetooth. I've upgraded by building from source, and the location is now /usr/libexec/bluetooth.
> Update oref0-bluetooth for pi

- lib/autotune/index.js
If `autosens_min` or `autosens_max` are not defined in profile, use the default recommended values of `0.7` and `1.2`.
As [reported on gitter](https://gitter.im/openaps/autotune?at=5c98bc356a3d2e230d20f654), running without this gives me:
```
Parameter      | Pump        | Autotune    | Days Missing                                                    
---------------------------------------------------------                                                    
ISF [mg/dL/U]  | 56.000      | 184.800     |                                                                 
Carb Ratio[g/U]| 14.000      | 14.000      |                                                                 
```
while with this I'm getting
```
Parameter      | Pump        | Autotune    | Days Missing …
```
> Apply default limits to autosens if none provided.

- lib/profile/targets.js
noticed on inspection, untested.
i'm also wondering why my temp target of >1 day only lasted about 18 hours - there's likely another issue in here (given the ns fetch limits to 24 hours, and i'm in mountain timezone, i'd guess its a timezone issue, but i'm not familiar with these date functions to see it...)
> use existing var

- bin/oref0-autotune-prep.js
I noticed autotune was not working properly and tracked it down to a mixed set of Zulu vs. local created_at timestamps in the treatments collection.
The Mongo sort in NS does not account for the different zones, so sort them locally before sending them to autotune-prep.
> Sort treatments before autotune

- bin/oref0-cron-every-minute.sh
- bin/oref0-cron-post-reboot.sh
Some times, (many times starting on first install) one can not connect the pi to WiFi, but can connect a screen.
This pr will give them 5 minutes before the screen is turned off, to allow them to either enable connection to WiFi, or disable screen turning off.
One more thing that is changes is that hat might be on spidev0.[01] so screen is shutdown in both cases. (without this change, on adafruit bonnet screen is not turned off at all).
> Turn off screen only after 5 minutes.

- bin/openaps-install.sh
- bin/openaps-packages.sh
- Remove calls to oref0-bash-common-functions.sh (it is not present on fresh installs)
- Add `die()` to the script so critical errors will stop the install
- Use nodesource (installs nodejs+npm) on all platforms except armv6 (pi0)
- Use `dev` openaps-packages.sh instead of $BRANCH (remove this before merging `dev` to `master`)
- Update npm to latest version on armv6 (pi0) using npm's self-updater (integrates https://github.com/openaps/docs/pull/1444)
> Fixes for openaps-packages.sh in dev

- bin/oref0-setup.sh
Mount the Edison's FAT32 partition to give us enough room to install golang.
> Use Edison's FAT32 Partition

- package.json
This fixes the issue of `Cannot find module 'network'` in the ns-looplog.
During the merge from sulkaharo's fork into the main dev branch it seems like this was left out because it was added in a later commit: https://github.com/sulkaharo/oref0/commit/b9cf6b84bde2a8d5bef9238c0306975ac9b92419#diff-b9cfc7f2cdf78a7f4b91a753d10865a2
> Add network module dependency

- bin/oref0-setup.sh
On my edison rig, i used to regularly get kernel panics.
This change makes the rig reboot whin the panic occurs and has made
looping interuptions a lot less frequent.
> Reboot rig after a kernel panic.

- bin/oref0-pump-loop.sh
- lib/profile/index.js
A new preference option is added enableEnliteBgproxy. When set to true
the bgproxy command will be call at the end of every loop sending the
glucose data to the medtronic pump.
This gives an option to setup low and high alarms directly from the
pumps and also see the glucose trend when offline.
To enable this feature:
- set enableEnliteBgproxy: true in preferences.json
- turn on the sensor feature in the medtronic pump.
- set the sensor id to 0000000 in Sensor setup
- select sensor->sensor start->Find lost sensor. Glucose should appear after a couple of
cycles.
> Bgproxy integration.

- bin/oref0-setup.sh
- www/app.py
installing flask-cors module and enabling in app.py allows a web-based script (such as IOS shortcut to running javascript) to access the rig's local web server for retrieving JSON information such as BG records, IOB, COB, Temp Basal/Duration, Battery Percentage, etc.
> install flask-cors - enable in www/app.py

- bin/oref0-setup.sh
Update setup to ensure bluez-tools is installed when CGM type of xdrip-js is chosen (Logger).
> add bluez-tools install for xdrip-js CGM type

- bin/oref0-bluetoothup.sh
Cleanup to oref0-bluetoothup to take jessie vs stretch into account and execute bluetooth control commands as appropriate for each OS.
> PedanticAvenger patch Stretch BT

- lib/determine-basal/determine-basal.js
- tests/determine-basal.test.js
As detailed at https://github.com/openaps/oref0/issues/1257, a failing Libre sensor, uploaded to Nightscout via LimiTTer/xDrip+, can result in falsely high and too-flat CGM readings and incorrect insulin delivery.  The existing mitigation for this, to avoid looping on completely unchanging CGM data, was insufficient in this case.  To further mitigate this and similar issues, this PR changes that check to look for CGM data that is changing less than 1 mg/dL/5m for 45m.  As shown at https://gist.github.com/scottleibrand/4c8c84d9989afc98bc92214a08e849f0, that would have been sufficient to prevent further insulin dosing in this case after CGM data falsely flattened out at 290 mg/dL.
This will likely result in occasional false-positives when BG is truly flat for an extended period of time, or …
> don't loop on too-flat CGM data

- bin/oref0-setup.sh
Remove old golang install before re-installing. 
Installing a new version of golang on top of an old version gives difficult to diagnose compile errors. 
Also changed the golang version to 1.12.5. I compiled the pump communication library with 1.12.5 while troubleshooting my issue, and everything worked well so might as well update it here i think.
> Remove old golang install before reinstalling.

- lib/autotune/index.js
- lib/profile/targets.js
Fixes #1271, where a temp target entry without a min/max target value would bypass the existing validity checks and result in insufficient insulin dosing for the duration of the temp target.
This PR skips any temp target values without a valid min (and max, if wide_bg_target_range is set) target value.
> Empty target fix

- bin/openaps-packages.sh
- bin/oref0-setup.sh
* Make sure node v8 is installed from nodesource
* Store `hardwaretype` in `preferences.json` 
* Switch openaps-menu installer for Radiofruit Bonnet back to openaps repo (needs merge of https://github.com/openaps/openaps-menu/pull/26)
> Debian Buster compatibility 

- bin/oref0-bluetoothup.sh
Fixes the newly added systemctl commands, whose start/restart bluetooth commands use an incorrect argument order, resulting in an inability for oref0-bluetoothup to automatically resolve bluetoothd issues.
> fix systemctl syntax in oref0-bluetoothup

- bin/openaps-install.sh
old line 12: the existing logic didn't make sense to me check for edison  but expire root so adjusting to check for root, expire root
old line 16-21: If you changed the password for 'pi' before running the script you'd never get to the part about changing root's password as it's disabled and locked by default and therefore `/run/sshwarn` will not exist.
new line 16-32: Check if we are running Raspbian, check the build date against the current password date for both pi and root. If they are the same, we are using default passwords and prompt for change. Checking them independently and only display information message once.
Let me know if you have questions.
> raspbian password checking adjustment (also expire correct user)

- bin/oref0-cron-every-minute.sh
By default, choose the first interface found with a control socket in the socket path.
> fix wrong interface choose

- bin/oref0-setup.sh
A small bug in `oref0-setup.sh` made it so that you couldn't proceed without providing a G4 Share serial number, breaking the use case where you don't have G4 Share. The problem is that `prompt_and_validate` takes an optional fourth argument for a default value, and if no default value is provided, then `prompt_and_validate` will re-prompt until you enter something that isn't blank.
> Allow G4 Share serial to be blank

- bin/oref0-upload-profile.js
When running `oref0-upload-profile` with an autotune report, the BG targets and ISF values in the report are rounded to the nearest whole number. This is not an issue if your autotune reports are generated in mg/dL units, however when using mmol/L a decimal is necessary to have precise ISF and BG target values. 
This PR solves these issues by changing the math for both ISF and BG targets to round to one decimal place if the profile units are in mmol/L. The rounding for mg/dL units is kept the same.
> Improved rounding of mmol/L units in oref0-upload-profile

- bin/oref0-bluetoothup.sh
- bin/oref0-online.sh
With this fix, I can maintain my bluetooth connection and continue looping where I otherwise wouldn't 2-3 times per day.  Running this code I get the following logs (and then the subsequent loop will reestablish my bluetooth connection).
```
Bluetooth hci name does not match hostname: sweetbasal. Setting bluetooth hci name.
hci0:	Type: BR/EDR  Bus: UART
BD Address: 58:A8:39:01:D7:40  ACL MTU: 1021:8  SCO MTU: 64:1
UP RUNNING PSCAN 
RX bytes:47078744 acl:91357 sco:0 events:46538 errors:0
TX bytes:8902971 acl:70445 sco:0 commands:7301 errors:0
Features: 0xbf 0xfe 0xcf 0xfe 0xdb 0xff 0x7b 0x87
Packet type: DM1 DM3 DM5 DH1 DH3 DH5 HV1 HV2 HV3 
Link policy: RSWITCH SNIFF 
Link mode: SLAVE ACCEPT 
Tue Sep 17 12:49:12 EDT 2019 Failed to set bluetooth hci name. Stop bluetoothd and allow next …
```
> Reestablish bluetooth connection after failure to set bluetooth hci name

- lib/determine-basal/determine-basal.js
and use minGuardBG otherwise
This is intended to address the problem posed in #1288, and I'm hoping simplifies the solution proposed there and makes it easier to validate.
> per #1288, only use minZTUAMPredBG if enableUAM

- bin/oref0-pump-loop.sh
- bin/oref0-setup.sh
When a rig is offline, it is using this code path and running oref0-set-device-clocks (which fails), but never getting to the part of oref0-pump-loop that runs oref0-set-system-clock. In order to make sure that the rig sets its time from the pump when NTP is unavailable, this simply adds a oref0-set-system-clock run after the attempt to oref0-set-device-clocks.
> run oref0-set-system-clock after oref0-set-device-clocks in case rig is offline

- bin/oref0-upload-profile.js
Currently, a case-sensitive comparison of strings 'mg/dl' and 'mg/dL' causes the profile uploader to multiply the values measured in mg/dl by 18.  So an ISF of 50 mg/dl in OpenAPS becomes an ISF of 900 mg/dl in Nightscout.  And similarly, a target of 90 mg/dl in OpenAPS becomes a target of 1620 mg/dl in Nightscout.   This PR fixes that issue.
> Fix values in mg/dl erroneously multiplied by 18 in profile upload to NS

- bin/oref0-upload-profile.js
Not sure if these are absolutely required, but safer to check for undefined variables.
> Add undefined checks to NS profile uploader

- bin/oref0-mraa-install.sh
- package.json
Slightly modified from the 0.6.0 installer, addresses https://github.com/openaps/oref0/issues/1270
Tested on Pi (Debian Buster) + Explorer HAT, could use testing on Edison (jessie & stretch) + Explorer Board.
> Standalone MRAA installer for OpenAPS v0.7.0

- bin/ns-status.js
- bin/oref0-ns-loop.sh
- lib/determine-basal/determine-basal.js
- logrotate.openaps
One repeated request from researchers is to be able to tell what preferences a user has enabled, and what version of oref0 they're running.  This uploads such information to the Nightscout devicestatus collection, so it can be included if the user chooses to donate their data to the OpenAPS Data Commons or similar. Sensitive PII from preferences.json is redacted prior to upload.
> Upload preferences.json and oref0 version to devicestatus

- bin/oref0-setup.sh
- lib/determine-basal/determine-basal.js
So this is actually a step towards what I'm hoping to implement, but I think the `enable_smb` logic should be refactored to make it easier to read and add additional SMB toggles for more customize-ability in the future. 
Unfortunately my oAPS rigs are broken (radios are dead), so I'm not able to test this in oAPS but I have this running in AAPS and it's running with no issue. Would welcome some testing to make sure I didn't accidentally change some logic.
> Refactor enable smb in determine-basal.js

- bin/oref0-pump-loop.sh
Needed in order to delete the file if the rig was booted after a long time.
> Call pumphistory_daily_refresh also in the case of a failure.

- bin/oref0-calculate-glucose-noise.js
- bin/oref0-pump-loop.sh
- lib/calc-glucose-stats.js
- lib/glucose-stats.js
- lib/profile/index.js
- package.json
- tests/glucose-noise.js
- tests/iob.test.js
This adds the option for oref0 to calculate the glucose noise level prior based on the glucose history.
It is disabled by default and controlled with the calc_glucose_noise preference.
> Add ability to calculate glucose noise

- lib/determine-basal/determine-basal.js
> Remove aCOBpredBGs (accelerated carbohydrate absorption) as it is not used anymore.

- lib/glucose-stats.js
- tests/glucose-noise.js
This makes the noise calculation a little more sensitive to trend direction changes by inserting a missing lastDelta assignment used to increase the weight of the glucose deltas.
> fix glucose-noise lastDelta logic error

- lib/determine-basal/determine-basal.js
Add more code comments giving an overview of what determine-basal is doing. Also removes some old comments and TODOs that we're never likely to do, and removes an old unused var missed in a previous cleanup.
> More comments

- lib/determine-basal/determine-basal.js
flat CGM data isn't really an error, just a reason to dose neutrally
> update too-flat language

- lib/glucose-get-last.js
- tests/get-last-glucose.test.js
There's a bug when we are looking at the undefined `then` entry when parsing the date for `now`. This PR fixes that bug, does a slight refactor to reduce bugs like this in the future, and adds a test to make sure we're falling back to the correct `dateString` property.
> Fix bug when parsing most recent date

- bin/oref0-cron-every-15min.sh
Added code to shutdown a pi based rig when battery level is low. I tested this code on my pi rig with explorer HAT several times using my lab bench power supply and one time with a standard 18650 cell.
> Add a shutdown function for pi based rigs

- bin/oref0-cron-every-minute.sh
Today, oaps stopped uploading data to NS, therefor I thought that it stopped working.
A small debug showed that ns-loop stopped running, and specifically, the following process got stuck:
root     14207 14063  0 37727 38252   0 16:23 ?        00:00:25 node /usr/local/bin/oref0-get-ns-entries cgm/ns-glucose-1h-temp.json https://snir-dev.herokuapp.com 911eea185f5c758ac275687da8b7eab50ad720e3 1
It seems that on pi-zero this process might be running up to 6-7 minutes (I saw it once running for 20 minutes), so killing it after 10 minutes seems reasonable.
> kill ns loop if it is running more than 10 minutes

- lib/glucose-get-last.js
This was a failed attempt to fix #1265, but would probably be a good idea regardless.
> Ignore glucose null

- bin/oref0-online.sh
I want to show the public ip in my system menu on the disply and don't want to do an extra ping :)
This code is tested on my pi rig with explorer-HAT (for around two weeks).
> Add public ip information to status file

- bin/oref0-get-ns-entries.js
As far as I can tell the PR https://github.com/openaps/oref0/pull/1248 introduced a regression for users with Dexcom G6 with share2 and Nightscout that use token based authentication for authenticating their rig to Nightscout.
Example logfile:
```
Starting oref0-ns-loop at Mon Dec 30 11:39:02 CET 2019:
Connected to 192.168.1.1, testing for xDrip API availability
Load from local xDrip timed out, likely not connected to xDrip hotspot
SyntaxError: Unexpected end of JSON input
at JSON.parse (<anonymous>)
at /root/src/oref0/bin/oref0-get-ns-entries.js:136:30
at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:511:3)
Loading CGM data from Nightscout failed null
Connected to 192.168.1.1, testing for xDrip API availability
Load from local xDrip timed out, likely not connected to xDrip hotspot …
```
> Fix cgm with share2 via nightscout with tokenbased authentication with oref 0.7.x (regression)

- bin/oref0-get-ns-entries.js
Twice in the last week we have had oref0-get-ns-entries hang in the call to request for an hour or more. 
This puts in a 90 second timeout to the call to request to prevent it from hanging.
> Add timeout to oref0-get-ns-entries request call

- bin/oref0-setup.sh
Fixes an issue with new installs where log shortcuts are not added to .bash_profile, because the `oref0-log-shortcuts.sh` script only works on existing files.
> Make sure .bash_profile exists

- bin/ns-status.js
- bin/oref0-ns-loop.sh
Before this checkin, ns-loop created the status data, and uploaded it to nightscout (if possible).
But in case of failure, the file will get overwritten.
This means that in the case of no internet, OAPS decisions get lost.
This checkin fixes it by adding timestamps to the files.
When internet is available, the files will be uploaded according to the correct order.
Files older than a day will be deleted.
Testing:
I have prevented uploading of files for a few hours, and when it was enabled again, data was shown correctly in nightscout site.
Decreased timeout, and saw the files being deleted.
> Upload NS status when possible.

- lib/determine-basal/determine-basal.js
- lib/profile/index.js
- tests/command-behavior.tests.sh
adv_target_adjustments was an early experiment, prior to the ZTpredBG changes, attempting to reduce highs. as it exists today, it does not succeed in reducing highs more than it increases lows. For example, in a 7-day oref0-backtest simulator run, it increased % time <70 by 2.6% while only reducing % time >180 by 0.8%.
This PR deprecates and removes adv_target_adjustments to clean up code in preparation for other efforts to accomplish the same thing (for example by extending the ZTpredBG work).
This PR also reorders some code (per earlier TODO comments) to make it more readable.
> Deprecate and remove support for adv_target_adjustments

- lib/profile/index.js
- lib/profile/targets.js
- tests/command-behavior.tests.sh
- tests/profile.test.js
Wide BG target ranges result in worse outcomes than a single BG target (at a preferred point within the wider range), as they prevent OpenAPS from taking earlier action to correct high and/or low BG.
In order to simplify code paths, allow for easier testing, and make room for future improvements, this PR removes support for wide_bg_target_range and max_bg, and instead sets target to min_bg (which has been the default behavior for some time).
This PR does not (yet) deprecate separate high and low temporary targets, but that would be an obvious next step.
> remove deprecated support for max_bg and wide_bg_target_range

- bin/openaps-install.sh
- bin/openaps-packages.sh
- bin/oref0-setup.sh
- Changes the way nodejs/npm are installed: Edison rigs will get it v8 from nodesource (Jessie/Stretch), Pi rigs will get it from the distro (Raspbian Buster)
- openaps toolchain will be installed from the latest version on git, rather than via pypi.
> Installer fixes

- bin/mm-format-ns-treatments.sh
- bin/ns-status.js
- bin/oref0-bash-common-functions.sh
- bin/oref0-cron-every-15min.sh
- bin/oref0-cron-every-minute.sh
- bin/oref0-get-ns-entries.js
- bin/oref0-normalize-temps.js
- bin/oref0-ns-loop.sh
- bin/oref0-setup.sh
- bin/oref0-shared-node-loop.sh
- bin/oref0-shared-node.js
- bin/oref0-upgrade.sh
- lib/require-utils.js
- package.json
Replacement for #1359 and #1352. Installs socat on all platforms so shared-node will work.
> shared-node

- lib/oref0-setup/pancreabble.json
Pancreabble can't find clock.json and glucose-unzoned.json files.
> Fix pancreabble config paths

- lib/iob/history.js
Fix for #1362 to accurately calculate IOB for Omnipod Loop users running Autotune from the `amount` field added to Temp Basal records to record how much insulin was actually delivered while the temp basal was running.
Needs further testing. Side-by-side autotune runs on a single day's worth of Omnipod Loop data show consistent small differences in calculated IOB, resulting in some minor differences in recommendations.
> calculate effective temp basal rate for Omnipod Loop

- lib/determine-basal/determine-basal.js
- lib/profile/index.js
As per @tynbendad  https://github.com/openaps/oref0/issues/1278#issuecomment-536225039, we also run into this issue regularly with fast carbs and bgs < 6 mmol/L.
So added a hidden optional % threshold to disable SMB.
Tried this out for the past 24hrs and works as normal at 20%, RigToo running updated % threshold, MealsDev2 running Dev.
```
Aug 21 12:48:56 RigToo pump-loop.log maxDelta 1.4 > 20% of BG 5.9 - disabling SMB
Aug 21 12:48:57 RigToo pump-loop.log "minPredBG 11.3, minGuardBG 6.9, IOBpredBG 11.8, UAMpredBG 13.8; maxDelta 1.4 > 20% of BG 5.9: SMB disabled; Eventual BG 13.8 >= 6.0, temp 0.35<1.6U/hr. "
Aug 21 12:51:06 MealsDev2 pump-loop.log maxDelta 1.4 > 20% of BG 5.9 - disabling SMB
Aug 21 12:51:07 MealsDev2 pump-loop.log "minPredBG 11.2, minGuardBG 6.9, IOBpredBG 11.6, UAMpredBG …
```
> maxDelta bg % threshold as hidden preference

- bin/ns-status.js
There is a corresponding NS PR to use the mills fields if they are available to drastically reduce the number of times moment has to parse the date strings when scrolling in NS.
> Add mills to status upload to reduce NS client workload

- bin/nightscout.sh
I don't see anywhere this is used, so it should have no impact.  However, for consistency, this corrects the latest-entries-time section of nightscout.sh.
> Correct NS Query

- bin/oref0-setup.sh
Quick fix for a dependency issue.
There is probably a bit cleaner solution, but this works for the moment.
> Fix issue 1377, install correct version of py-parsedatetime

- bin/oref0-setup.sh
Recently I re-ran the setup script on DEV and ran into the parsedatetime error. I narrowed it down to what I think is a typo, there is a `===` when I believe `==` is what was meant. I modified this file locally and ran with no issues.
> equal sign typo

- www/app.py
As per @renegadeandy pull request https://github.com/renegadeandy/oref0/pull/1
just tested it and it works nicely, so making PR for Dev.
> Update app.py to show sgv via workaround

- bin/oref0-ns-loop.sh
This adds the logic to handle Nightscout instances with default denied read permissions.
> Fix oref0-ns-loop.sh pushover_snooze NS authorization

- bin/oref0-autotune-prep.js
- bin/oref0-autotune.sh
In several Dutch and English Facebook groups, I see a growing number of posts of Autotune(Web) seemingly not working. I thought we can share some insight on this error, help people to resolve this themselves, and reduce support requests by implementing two small fixes. Did my best, see below :)
**Error message**
When using Autotune(Web) some people mention error message "SyntaxError: Unexpected token u in JSON at position 0".
**Analysis**
People do not understand the technical error message. They search and/or start a support request in a Facebook group. I have analyzed several full error messages, most of the time I see BG-data is missing for entered dates (technically: epoch timestamp). For people, Autotune(Web) was always working and suddenly does no anymore, how come? And why would …
> Improve error message on Autotune run without BG-data

- bin/oref0-autotune-prep.js
I found that my rig wasn't autotuning anymore, and hadn't for a few months. When I tried to run manually, I got:
```
Grabbing NIGHTSCOUT treatments.json and entries/sgv.json for date range...
Query: https://geekygirl-nightscout.herokuapp.com entries/sgv.json find%5Bdate%5D%5B%24gte%5D=1633766400000&find%5Bdate%5D%5B%24lte%5D=1633852800000&count=1500
-rw-r--r-- 1 root root 104010 Oct 16 22:43 ns-entries.2021-10-09.json
Query: https://geekygirl-nightscout.herokuapp.com treatments.json find%5Bcreated_at%5D%5B%24gte%5D=2021-10-08T06:00-04:00&find%5Bcreated_at%5D%5B%24lte%5D=2021-10-10T18:00-04:00
-rw-r--r-- 1 root root 448846 Oct 16 22:43 ns-treatments.2021-10-09.json
oref0-autotune-prep   ns-treatments.2021-10-09.json profile.json ns-entries.2021-10-09.json profile.pump.json > …
```
> Fix autotune prep error

- lib/determine-basal/determine-basal.js
as described in #1401 we have a possibility of zero or negative ratio on low TT and halfBasalTarget.
This ensures that we don't get over the autosens_max even in these situations
getting multiplication less or equal to 0 means that we have a really low target with a really low halfBasalTarget
with low TT and lowTTlowersSensitivity we need autosens_max as a value
we use multiplication instead of the division to avoid "division by zero error"
> per #1401 set highest sensitivity on low TT and halfBasal

- bin/ns-delete-old-devicestatus.sh
openaps uploads a lot of date to nightscout.
This script makes it easy to delete old entries.
To use it simply run:
bin/ns-delete-old-devicestatus.sh delete <NIGHTSCOUT_HOST>  <asn1 of API_SECREAT>
> Add a script to delete device status entries that are older than 2 months.

- lib/determine-basal/determine-basal.js
include missing parameters in rT.rerason to fix #1405
> rT.reason extended with missing values

- bin/oref0-ns-loop.sh
- bin/oref0-pump-loop.sh
The various cp *.json $dir_name commands introduced for testing/debugging shared-node are writing hundreds of MB per day.  Commenting out the cp commands to avoid quickly filling up the rigs' disks.
> comment out shared-node cp to avoid full disk

- bin/oref0-autosens-loop.sh
- bin/oref0-bash-common-functions.sh
- bin/oref0-cron-every-minute.sh
- bin/oref0-ns-loop.sh
- bin/oref0-pump-loop.sh
- bin/oref0-pushover.sh
- lib/determine-basal/determine-basal.js
This PR cuts down on spurious/duplicate carbsReq pushover noise:
- don't send carbsReq alerts if COB is zero due to clock data parsing error
- run pushover from pump-loop immediately after completing a loop
- check Nightscout for pushover snoozes (created when another rig has already sent a pushover) immediately before sending one
The latter two combine to eliminate the race condition where two rigs would both send pushover alerts if they completed loops within a minute or two of each other (before cron had a chance to run pushover, update the snooze file to Nightscout, and then run ns-loop to download it to the other rig).
> carbsReq pushover improvements

- bin/openaps-install.sh
- bin/openaps-packages.sh
- bin/oref0-setup.sh
Note: This PR has changed somewhat significantly since inception. The "very minor" changes listed below have been removed to keep the focus on changes to node/npm install improvements. The original text otherwise follows, but please see the comments for relevant context.
---
- Escape quotes that are themselves in a quoted string. Before, these quotes would not print, but it did not cause any errors or other unexpected behavior.
- Moved a comment to (what I think is) the right place
- Remove the nodesource JS installation (in the case of edison boards) from the install script, as it is already done in the openaps-packages script and is not needed until then
- The biggest change of this PR. Instead of Installing `nodejs` and `npm` from the package manager, we instead install [the node …
> Improved handling of node installation (& miscellaneous improvements)
