- bin/oref0-mint-max-iob.sh
- package.json
Should help documenting setup instructions.
> add very simple max_iob creation tool

- bin/loop.sh
Guess we haven't removed loop.sh from dev yet, so doing that now.
> rm old loop.sh

- bin/oref0-determine-basal.js
- tests/determine-basal.test.js
with this getting glucose from NS is much cleaner, no more json conversion
> Support the NS sgv field to avoid having to convert in a custom way

- bin/oref0-determine-basal.js
- tests/determine-basal.test.js
We should probably also write some tests for the things I touched that don't have tests already...
> Reason fixes

- bin/ns-status.js
- package.json
Related to https://github.com/nightscout/cgm-remote-monitor/pull/1375
> tool to format loop/pump status to upload to NS

- bin/oref0-determine-basal.js
- lib/basal-set-temp.js
- lib/determine-basal/determine-basal.js
- lib/glucose-get-last.js
- package.json
- tests/determine-basal.test.js
- tests/get-last-glucose.test.js
- tests/set-temp-basal.test.js
Before we can consider merging #36, will need to do some testing and most likely collaborative work, so pulling @LorelaiL's work into an openaps/oref0 wip branch for us to work off of.
> Pull @LorelaiL's extract_module refactor into branch

- bin/oref0-determine-basal.js
rt.reason avgdelta added toFixed
move console.log result
add if/else
add maxSafeBasal into reason
> A bit of formatting if/else

- lib/determine-basal/determine-basal.js
- tests/determine-basal.test.js
This introduces the concept of "expected delta" as a replacement for BGI/2, so that rather than a binary threshold, we gradually phase in high temps when the PWD is not falling fast enough, or low temps when not rising fast enough.  Fast enough is defined as BGI, adjusted for whatever additional delta (rate of rise/fall) would be required to get to target over the course of DIA.  So if you're 300 with a 120 target, 40 ISF, 3h DIA, and no IOB / insulin activity, you'd need to be falling at 5mg/dL per 5m before it completely phases out the high temp.  This should help with situations where IOB is way off from what it "should" be, especially when riding high without any correction bolus IOB.
> Expected delta

- bin/oref0-determine-basal.js
- bin/oref0-get-profile.js
- bin/oref0-meal.js
- bin/oref0-normalize-temps.js
- bin/oref0-pebble.js
- bin/oref0.sh
- lib/determine-basal/determine-basal.js
- lib/glucose-get-last.js
- lib/iob/total.js
- lib/meal/history.js
- lib/meal/index.js
- lib/meal/total.js
- lib/profile/carbs.js
- lib/profile/index.js
- lib/profile/isf.js
- package.json
- tests/determine-basal.test.js
- tests/iob.test.js
> Meal assist

- tests/determine-basal.test.js
> added test to make sure we don't high temp when rising too slowly

- bin/ns-status.js
using the format openaps://hostname
> add device field to NS status

- bin/ns-status.js
so 1 missing file doesn't cause the entire status uload to fail
> safe require the NS stus inputs

- bin/oref0-raw.js
- lib/with-raw-glucose.js
- package.json
- tests/with-raw-glucose.test.js
I have this working now, found a couple little things while getting it going
> rawbg support part 2

- bin/ns-status.js
- bin/oref0-normalize-temps.js
- lib/bolus.js
- lib/pump.js
* less treatment spam in NS
* BG Check event type
* fixes for meal bolus / correction bolus / carb correction detection
> Some treatment cleanup

- lib/pump.js
> goodbye Sara6E

- lib/bolus.js
@scottleibrand this updates ama with dev, but basically ignores the conflicting changes in #76 that I think you handle differently in ama
> resolve conflict in bin/oref0-detect-sensitivity.js between dev and ama

- bin/ns-status.js
it's not needed with fixes in current version of mmeowlink
> remove 'recieved' hack

- bin/oref0-get-profile.js
- bin/oref0-mint-max-iob.sh
- lib/profile/index.js
First step. I think this is the best way to start introducing more configuration into the `profile` (e.g. things like `disable_neutral_temps`).
> Rename max_iob.json to preferences.json

- bin/oref0-get-profile.js
- lib/basal-set-temp.js
- lib/profile/index.js
> Make neutral temp basals configurable

- lib/meal/history.js
Should fix the deduper deleting carb events due to boluses
> Only check for carb events when deduping carb events.

- tests/iob.test.js
Increase code coverage from 79.46% to 86.93%
> Increase test coverage by testing temp basal calculations

- tests/iob.test.js
=============================== Coverage summary ===============================
Statements   : 87.92% ( 444/505 )
Branches     : 81.82% ( 270/330 )
Functions    : 95% ( 19/20 )
Lines        : 89.26% ( 432/484 )
==============================================================================
> A couple more temp basal IOB tests; lib/iob/history.js is now pretty well covered

- bin/oref0-reset-git.sh
Fixes #142.  Please test and 👍 for merge to dev.
> Check git diff as well as git status for git corruption

- bin/ns-status.js
- bin/oref0-get-profile.js
If I've got this right, it will fix the conflict and merge in my changes from this evening.
> Fixing merge ama

- bin/oref0-get-profile.js
model_data was populated but never used.
> Add model_data to profile, fix usage string

- bin/oref0-get-profile.js
Using the new yags commands format
> Bring back export-defaults and update-preferences commands

- tests/iob.test.js
The new tests were only testing the default
> Added a test for high bolussnooze_dia_divisor

- .travis.yml
- Makefile
- package.json
Let's see if the PR triggers the reports already :)
> Makefile changes to enable coveralls reporting

- package.json
Add clockset.sh to the npm package.
> Add clockset.sh to npm package.

- lib/iob/history.js
- lib/profile/basal.js
- package.json
- tests/basal.test.js
- tests/iob.test.js
Same as https://github.com/openaps/oref0/pull/199, but with tabs converted to spaces and extra end-of-line spaces removed.
> Sulkaharo wip/split temp basals

- bin/oref0-conditional-run.sh
- lib/determine-basal/cob-autosens.js
- lib/profile/index.js
- lib/profile/isf.js
- package.json
Not dealt with properly: meal impact overlapping ISF change
> Use correct ISF for any time of day when calculating autosens

- bin/oref0-conditional-run.sh
- lib/determine-basal/cob-autosens.js
- lib/profile/index.js
- lib/profile/isf.js
- package.json
@sulkaharo any reason not to go ahead and merge this?  It's looking good to me...
> Use correct ISF for BGI; new oref0-crun tool

- bin/oref0-setup.sh
As this only affects oref0-setup.sh, I'm gonna go ahead and merge it.
> oref0-setup fixes

- bin/oref0-meal.js
Fix #210. This should keep AMA from being too aggressive due to https://github.com/openaps/openaps/issues/111
Cc @ryanchen26
> Validate carb ratios are reasonable

- bin/oref0-setup.sh
- lib/oref0-setup/alias.json
- lib/oref0-setup/device.json
- lib/oref0-setup/report.json
Fixes https://github.com/openaps/oref0/issues/215 (thanks @pietergit !)
I've tested that this works backwards compatibly with mg/dL.
@sulkaharo (or anyone else on mmol/L) you want to test this and confirm it works for you?
> Support both mmol/L and mg/dL

- bin/oref0-calculate-iob.js
- bin/oref0-setup.sh
- lib/iob/index.js
- lib/oref0-setup/alias.json
- lib/oref0-setup/device.json
- lib/oref0-setup/mdt-cgm.json
- lib/oref0-setup/report.json
Initial attempt at MDT CGM support, based on commands provided by @bender1061.  John (or anyone else with Enlite), can you pull the oref0-setup branch and test whether this actually works?  I only have Dexcom myself, so I've just been able to test that the script itself works, not whether the resulting loop works.
> MDT CGM support

- bin/oref0-setup.sh
Adding note about avoiding trailing slash in NS URL entry
> Warning about trailing / on NS URL

- bin/oref0-determine-basal.js
Tweaking the error message since most people are misreading this one. @emsamom since you last experienced this, let me know if this makes it more obvious? + anyone else, of course.
> Adjust error about BG data being too old

- lib/iob/calculate.js
> Fix activityContrib

- bin/oref0-setup.sh
- package.json
Targeting a 0.3.1 patch release with these for this weekend.
> oref0-setup bug fixes and minor improvements

- lib/determine-basal/cob-autosens.js
This needs some testing against real-world missing data.
> interpolate missing glucose data for autosens and AMA

- bin/bt-pan
- bin/oref0-dex-is-fresh.sh
- bin/oref0-dex-time-since.sh
- bin/oref0-dex-wait-until-expected.sh
- bin/oref0-online.sh
- bin/oref0-setup.sh
- lib/oref0-setup/alias.json
- lib/oref0-setup/cgm-loop.json
- lib/oref0-setup/report.json
- logrotate.openaps
- package.json
based on https://github.com/openaps/docs/wiki/CGM-Loop-with-openxshareble-scratchpad
still need to figure out if we're going to do wired G4 and G5 NS upload the same way, or something else.
> add openxshareble support (with NS upload)

- bin/oref0-setup.sh
Thanks @woodtrevor for the catch & testing the fix.
> sudo pip install mmeowlink hotfix

- bin/oref0-setup.sh
Related change: https://github.com/openaps/openaps/pull/112
I don't currently have a box to test this on, but "it should work" (TM). I'll try sort one out this evening.
> Add radio_locale support

- bin/oref0-setup.sh
I got sed to modify /etc/rc.local and incorporated them here.  This needs testing, especially to make sure there isn't conflict with the other ble language in there, but I think it is ok.  I'll be starting another Edison from scratch, hopefully tomorrow and will be able to more fully test. Others should too, however.
> bluetoothd for shareble

- bin/oref0-setup.sh
I put the sed commands within an "if ..fi" structure instead of your suggested double pipes for clarity. It increases the number of lines a bit more but keeps lines shorter and obfuscates a bit less (at least in my mind). There is now checking for each new line and each line is only added if absent.   So far my tests are showing that this portion behaves as expected. Most permutations have been tested, but not all.
> better file handling for mods to /etc/rc.local

- bin/oref0-setup.sh
- lib/oref0-setup/edisonbattery.json
Change to go to dev branch. and not use cron. Also add script to prompt for BT Mac address
> Edison battery

- bin/oref0-setup.sh
- lib/oref0-setup/alias.json
- lib/oref0-setup/device.json
- lib/oref0-setup/report.json
- lib/oref0-setup/xdrip-cgm.json
Added support for xdrip as cgm source, using xDripAPS microservice.
> Adding xdrip offline support

- bin/oref0-detect-sensitivity.js
- bin/oref0-get-profile.js
> Support loading ISF and BG targets in mmol/L

- bin/oref0-setup.sh
temporary workaround for
https://github.com/oskarpearson/mmeowlink/issues/55
> fix workaround for ww pumps

- bin/oref0-online.sh
this has proved more stable for me across some wifi netoworks, BUT NEEDS TESTING BY OTHERS
> restart networking completely instead just cycling wlan0

- bin/mm-format-ns-glucose.sh
- bin/mm-format-ns-profile.sh
- bin/mm-format-ns-pump-history.sh
- bin/mm-format-ns-treatments.sh
- bin/mm-format-oref0-glucose.sh
- bin/mm-stick.sh
- bin/nightscout.sh
- bin/ns-dedupe-treatments.sh
- bin/ns-get.sh
- bin/ns-upload-entries.sh
- bin/ns-upload.sh
- bin/oref0-conditional-run.sh
- bin/oref0-copy-fresher
- bin/oref0-fix-git-corruption.sh
- bin/oref0-ifttt-notify
- bin/oref0-mint-max-iob.sh
- bin/oref0-reset-git.sh
- bin/oref0-reset-usb.sh
- bin/oref0-set-device-clocks.sh
- bin/oref0-set-system-clock.sh
- bin/oref0-setup.sh
- bin/oref0-truncate-git-history.sh
- bin/oref0.sh
> Revert "Exit scripts when variables under or functions fail"

- bin/oref0-setup.sh
with a reinstall i noticed two bugs that caused ww pump not to work and also a problem with the dexusb script which i thought was fixed in git, but wasn't
> fix ww pump and dexusb with small changes

- lib/oref0-setup/mdt-cgm.json
... to always run on failures, even if wait-for-long-silence fails
> Fix MDT mmtune

- bin/oref0-setup.sh
To run: `bash ~/myopenaps/oref0-runagain.sh`
> Saving interactive setup output to a file that can be run later

- lib/iob/history.js
It may also make sense to look for !(current.timestamp) && current.insulin since I believe HAPP may give you the ability to edit the "Entered by" string (need to confirm that though).
> Updated for HAPP insulin treatments parsing

- tests/profile.test.js
Don't merge, trying to make coverall happy.
> Coverall changes

- bin/oref0-setup.sh
use `npm run global-install` otherwise
Helps address https://github.com/openaps/oref0/pull/302
> install oref0 from npm when on master branch

- bin/oref0-online.sh
If we get a response from icanhazip.com that is obviously not an IP address, go ahead and try to connect to Bluetooth.
> reject captive portal redirects

- bin/oref0-setup.sh
I've never done this before, so someone check me on this. Seems pretty straightforward, though.
> Add btmac into oref0-runagain

- bin/oref0-setup.sh
Copy of https://github.com/openaps/oref0/pull/380 with test fixes merged from dev
> Changes necessary for running autotune on OS X

- bin/oref0-setup.sh
Addresses https://github.com/openaps/docs/pull/635
@tomasboudr can you test this please?
> strip trailing / from URLs provided on command-line too

- bin/oref0-autotune.sh
> Automatically copy pumpprofile.json & autotune.json from profile.json

- bin/oref0-online.sh
Replace how we get the SSID, use iwgetid instead.
Replace how we the IP of the wlan and bnep interfaces to use the ip command.
> Changes to oref0-online

- bin/oref0-setup.sh
Also removes ShareBLE from the interactive prompts per @kdisimone's #398
> Rename G4-raw to G4-upload, and G4 to G4-local-only

- bin/ns-dedupe-treatments.sh
- bin/ns-get.sh
- bin/oref0-autotune.sh
- bin/oref0-online.sh
- bin/oref0-upload-profile.js
- lib/oref0-setup/alias.json
- lib/oref0-setup/device.json
- lib/templates/refresh-loops.json
This saves me significant metered data when I'm tethered.  It also seems to help when I'm out of the LTE coverage area.
> use compressed curl calls

- bin/oref0-setup.sh
I've had to manually set it to +x every time, so this will fix that for anyone with the issue (and not cause problems for those without)
> set oref0-runagain.sh as executable after move.

- bin/mm-format-ns-pump-history.sh
- bin/mm-format-ns-treatments.sh
- bin/nightscout.sh
- bin/ns-dedupe-treatments.sh
This cleans up a number of chained `json` calls to execute all operations in a single execution.
> don't do redundant JSON parsing

- bin/mm-format-ns-pump-history.sh
- bin/mm-format-ns-treatments.sh
- bin/nightscout.sh
- bin/ns-dedupe-treatments.sh
- bin/oref0-detect-sensitivity.js
- bin/oref0-pump-loop.sh
- bin/oref0-setup.sh
- lib/autotune-prep/categorize.js
- lib/determine-basal/cob-autosens.js
- lib/determine-basal/determine-basal.js
- lib/profile/index.js
Full description in issue https://github.com/openaps/oref0/issues/440
> Adjust target when high

- Makefile
- bin/mm-format-ns-pump-history.sh
- bin/mm-format-ns-treatments.sh
- bin/nightscout.sh
- bin/ns-dedupe-treatments.sh
- bin/oref0-autotune-prep.js
- bin/oref0-autotune.sh
- bin/oref0-detect-sensitivity.js
- bin/oref0-meal.js
- bin/oref0-pump-loop.sh
- bin/oref0-setup.sh
- lib/autotune-prep/categorize.js
- lib/autotune/index.js
- lib/determine-basal/cob-autosens.js
- lib/determine-basal/determine-basal.js
- lib/meal/total.js
- lib/profile/index.js
- tests/determine-basal.test.js
- tests/iob.test.js
> Floating carbs / UAM

- bin/oref0-setup.sh
- lib/basal-set-temp.js
- lib/determine-basal/determine-basal.js
adding pushover prompt questions
Saving pushover flags in runagain script
hidden microbolus enable prompt (for future use)
adding bt question
> Setup script

- bin/oref0-autotune.sh
restore "Copy tuned profile produced by autotune to profile.json for use with next day of data"
> restore cp of newprofile

- lib/determine-basal/determine-basal.js
set neutral temp when snoozeBG > target_bg, and lastCOBpredBG > target_bg
> SMB bolus snooze

- bin/oref0-setup.sh
> Mraa fix for dev

- bin/oref0-pump-loop.sh
This might help with #522 somewhat, but doesn't address the root cause.
> mmtune 25% of the time; remove unless() loop

- bin/oref0-pump-loop.sh
> Fix of Echo for MDT Pump-loop log

- lib/oref0-setup/alias.json
This should implement @jmcrawford's #529 cleanly against latest dev.
> Fix ns-meal-carbs argument order

- bin/oref0-autotune-export-to-xlsx.py
It makes more sense for this variable to be the autotune directory, but the code is written now for it to be the openaps directory. If I knew how, I'd update lines 140-142 instead, but that's beyond my skills :)
> Fix argument definition

- bin/oref0-pump-loop.sh
Add some additional output to show what oref0-pump-loop is doing, and improve retry logic in a few places.
> oref0-pump-loop reliability and debugging improvements

- bin/oref0-setup.sh
and only easy_install it if not
> check whether decocare-0.0.31 has been installed

- lib/iob/calculate.js
as discussed in the oref0 channel
> Remove double declaration of biobContrib

- bin/nightscout.sh
- lib/oref0-setup/report.json
This merges @thebookins' "Fix for missing temp targets and carb treatments for timezones east of UTC" to 0.6.0-dev for testing before we merge #614
> Timezone fix to 0.6.0-dev

- lib/determine-basal/determine-basal.js
This should help with situations like https://github.com/openaps/oref0/issues/604#issuecomment-322066796
> don't allow target_bg below 80

- bin/oref0-pump-loop.sh
#631 is open to merge this to dev, but I've tested it well enough to merge it to 0.6.0-dev.
> Always mmtune if pump_loop_completed > 15m old

- bin/oref0-log-shortcuts.sh
add edison battery level and cartridge insulin level to profile shortcuts. I find them both useful and imagine others might as well.
> 2 additional profile shortcuts

- bin/oref0-setup.sh
... and remove some outdated warnings about SMB
> autotune/autosens on by default; don't ask about ~/myopenaps

- bin/oref0-pump-loop.sh
IOB was not being properly recalculated after refreshing pumphistory after each loop.  This fixes that.
> recalculate IOB before re-doing smb-suggested.json

- bin/ns-get.sh
- bin/oref0-autotune.sh
wait...let me do other file and then test
> json to jq

- bin/ns-get.sh
- bin/oref0-autotune-prep.js
- bin/oref0-autotune-recommends-report.sh
- bin/oref0-autotune.sh
- lib/autotune-prep/categorize.js
- lib/autotune-prep/dosed.js
- lib/autotune-prep/index.js
- lib/autotune/index.js
There are some significant improvement to autotune that are currently in the dev branch, that make a big difference to tackle the previously-known issues around upward bias on ISF and carb ratio. Dev (0.6.0) is a ways out from release, so wanting to patch so one-off users of autotune and everyone on master can utilize the autotune improvements sooner.
> Autotune patch release to master (oref0 0.5.5 patch release)

- lib/determine-basal/determine-basal.js
- lib/iob/history.js
fix for https://github.com/openaps/oref0/pull/684#issuecomment-336717935
> fix remaining references to half_basal_target

- bin/oref0-setup.sh
https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2017-1000250
http://www.bluez.org/release-of-bluez-5-47/
> BlueZ update - min  version 5.47 (BlueBorne vulnerability fix)

- bin/oref0-online.sh
this commit ensures that we only shut down a local hotspot if `check_ip` returns `true`, and prevents cycling between BT PAN and local hotspot
> only stop hotspot if we have internet

- bin/oref0-log-shortcuts.sh
- bin/oref0-setup.sh
- lib/determine-basal/determine-basal.js
- lib/meal/history.js
- lib/meal/total.js
- lib/profile/index.js
Several people have reported A52 errors over time caused by SMB attempting to bolus while the pump bolus wizard is open, and in at least one case this resulted in OpenAPS being unable to read some boluses from pump history.  In order to minimize this risk, this PR sends ESC three times to the pump before issuing a microbolus, in order to cancel out of any bolus wizard or other menus before doing so.
In addition, the recommended method for using SMBs is to enter carbs via NS and easy bolus any desired up-front insulin (generally less than the full amount that would be recommended by the bolus wizard) and then let SMB fill in the rest as it is safe to do so.  For situations where the bolus wizard is preferred, such as for carb entry by inexperienced caregivers, or for offline use, we feel …
> A52 risk reduction

- lib/determine-basal/determine-basal.js
added some missing unit conversions, and added carb ration to the reason field
> Reason improvements

- lib/determine-basal/determine-basal.js
Forgotten profile object reference
> Fix "A52_risk_enable is not defined" error

- lib/profile/carbs.js
- lib/profile/index.js
- tests/profile.test.js
This could have surprising or dangerous effects when used with autotune or smb.
> Deprecate and remove profile.carbratio_adjustmentratio

- bin/oref0-online.sh
- bin/oref0-pump-loop.sh
- bin/oref0-setup.sh
If a wifi network is marked bad and we're still connected via BT, retry the wifi after an hour to see if the issue was transient.
Also, bash-completion for easier TAB TAB.
> retry bad_wifi after an hour

- lib/determine-basal/determine-basal.js
Fixes a bug that prevented the maxDelta > 20% of BG check from working.
> fix logic error in maxDelta

- lib/determine-basal/determine-basal.js
Couple of values missing conversion to mmol/l
> Convert threshold where appropriate in logging output

- lib/glucose-get-last.js
Propagate the noise field of glucose data so it can be used by determine_basal.
> Propagate the noise field.

- bin/oref0-version.sh
Add the forgotten line to actually fetch upstream before checking commits.
> oref0-version fetch upstream

- lib/bolus.js
- lib/meal/history.js
- lib/meal/total.js
Merge https://github.com/openaps/oref0/pull/810 to dev with a couple tweaks
> Process the Meal marker event from medtronic pump

- bin/ns-status.js
- bin/oref0-autotune-core.js
- bin/oref0-autotune-prep.js
- bin/oref0-calculate-iob.js
- bin/oref0-detect-sensitivity.js
- bin/oref0-determine-basal.js
- bin/oref0-find-insulin-uses.js
- bin/oref0-get-profile.js
- bin/oref0-html.js
- bin/oref0-mdt-trend.js
- bin/oref0-meal.js
- bin/oref0-normalize-temps.js
- bin/oref0-pebble.js
- bin/oref0-raw.js
- bin/oref0-set-local-temptarget.js
- bin/oref0-upload-profile.js
changed splice/pop to array element
cleaned up ns-status
> ns-status js format

- lib/iob/history.js
- tests/iob.test.js
Merge https://github.com/openaps/oref0/pull/819 to dev, with a modification to 
loop over all of pumpHistory to find matching TempBasalDuration if it's not adjacent.
> Basal record search

- bin/oref0-setup.sh
Automate the steps to install flask as a service so can monitoring your rig OFFLINE with an Offline web page
IPHONE USERS To access this from an iphone browser, enter something like the following: http://172.20.10:5000
ex : http://IP_address__rig:5000
> Automate the steps to install flask as a service

- bin/openaps-install.sh
- bin/oref0-setup.sh
This PR adds Explorer HAT support to oref0-setup.
> oref0-setup Explorer HAT support

- bin/oref0-setup.sh
- www/app.py
- www/templates/index.html
This merges #839 to dev, along with some minor tweaks as discussed there.
> Serve offline web page with flask

- bin/oref0-pump-loop.sh
- lib/determine-basal/determine-basal.js
Because x.y minutes bugs me :P 
Still need to check the regex stuff works properly and sort out tabs vs spaces - don't merge yet, I created this PR already in case anyone wants to comment.
> Display seconds in SMB wait time

- bin/oref0-mdt-trend.js
Resolved an order of comparison issue for negative trends when calculating the mdt direction arrow values.
> fix mdt direction calculation for negative trending

- bin/oref0-pump-loop.sh
(introduced by automatic merge conflict resolution)
> remove duplicate function definitions

- bin/oref0-pushover.sh
Set Pushover Priority to urgent to ensure user sees the message.
> Pushover Priority to Urgent

- bin/oref0-autotune-core.js
- bin/oref0-autotune.sh
- bin/oref0-setup.sh
- package.json
Format the profile when copying it to settings to aid visually comparing to pump profile.
> Format Autotune Output Profile

- bin/oref0-pump-loop.sh
This will make sure a default frequency doesn't overwrite the last known 'good' frequency.
> Check for usedDefault in mmtune

- lib/iob/history.js
- tests/iob.test.js
This pull request updates history.js to recognize pump suspensions when calculating IOB.
To enable the new feature, set the preference suspend_zeros_iob to true.
> Enable IOB calc to recognize suspends

- lib/determine-basal/determine-basal.js
> default remainingCATime to remainingCATimeMin if meal_data.carbs == 0

- lib/profile/index.js
The lib/profile/index.js needs a default for the preference for the new preference to be pulled into the profile.json file.
> Fix suspend zeros iob preference

- README.md
> Fix a href

- lib/profile/index.js
After successfully using this feature for a while, I recommend we make it the default behavior.
> Changed suspend_zeros_iob default to true.

- bin/oref0-pump-loop.sh
This is an interim solution to get bolus wizard carb entry working, until we can test out and merge https://github.com/openaps/oref0/pull/932
It's not super efficient, but I've tested it and it works.
> use just pumphistory-24h-zoned for COB calc; refresh it every 10-30m

- bin/oref0-autosens-loop.sh
- bin/oref0-get-profile.js
- bin/oref0-ns-loop.sh
- bin/oref0-pump-loop.sh
- bin/oref0-pushover.sh
- lib/oref0-setup/cgm-loop.json
- lib/profile/targets.js
Started with #932 and made some tweaks to resolve merge conflicts, and improve logging and error handling. @alimhassam can you test this out?
> Fast pump history

- bin/oref0-setup.sh
remove existing `bluez-5.48.tar.gz` in case of failed wget so subsequent commands run.
> Update oref0-setup.sh for the edgecase of failed wget

- lib/iob/calculate.js
- tests/iob.test.js
* remove unused code
* create separate function for iobCalcExponential
* use consistent variable names in iobCalcBilinear and iobCalcExponential
* add comments and references 
* provide more intuition for bilinear activity calculation
* (deleted a few blank lines in iob.test.js, too)
> refactor calculate.js

- bin/oref0-pump-loop.sh
- bin/oref0-set-device-clocks.sh
A re-do of #924 to handle invalid or misunderstood clock.json data & remove any remaining typos.
> Fix date routine, corrected/operational

- www/app.py
glucose file check to use xdrip glucose data if newer than monitor glucose data
> offline monitor - use xdrip bg data if more recent than monitor

- bin/oref0-setup.sh
cherry pick small fixes from go-dexcom branch, and relax the arm version check.
> Go cherry pick

- lib/iob/history.js
- lib/iob/index.js
- tests/iob.test.js
Merge #955 to my current feature branch first before merging it to dev for wider testing.
> Use Current Time Input Consistently in IOB Lib

- bin/oref0-pump-loop.sh
Revert the outcome of this test to its original behavior.
> Revert change

- bin/oref0-setup.sh
Add -y flags to the rest of the apt-get commands to bypass y/n prompts.
> autoconfirm apt-get

- bin/oref0-setup.sh
Removed references to $HOME/myopenaps and replaced with variable
$directory which has the actual install directory in it. Resolved
missing directory error on install
> Change static assignment of installation directory

- www/app.py
support similar to xdrip+, for offline use with watchfaces, etc.
> add sgv.json?count=# route

- bin/oref0-setup.sh
I'm getting a `syntax error: unexpected end of file` running dev `openaps-setup` on a Pi + Explorer HAT. 
I think this commit left an unmatched `if`: https://github.com/openaps/oref0/commit/f92a01ead0e5186270920b27d61d2282d178569c#diff-704a2fd9a43fd79bf52037b1668c146d
> fix syntax error

- bin/oref0-pump-loop.sh
Changed if statement to check preferences.json instead of openaps.ini for used cgm device.
> real fix  if_mdt_get_bg

- bin/oref0-pump-loop.sh
* Add SPI reset
* Add logging function
* Enable independend timer for emergency actions
(Tested for around two weeks on my Pi0+ HAT + MDT)
> Update duty cycling code

- bin/oref0-setup.sh
- tests/json-wf.sh
This updates #1043 to work with 0.7.0-dev
> advanced BT tethering pref to 0.7.0-dev

- bin/oref0-pump-loop.sh
Added suggestions from https://github.com/openaps/oref0/issues/1058 and removed emergency actions since a different script is rebooting when radio problems occur.
> Update duty cycle code

- bin/oref0-get-profile.js
This fixes the error in #1099 .
It also consolidates the usage string to one location in yargs.
> Oref0 get profile arg parsing

- bin/oref0-autotune-recommends-report.sh
- lib/autotune/index.js
A simple attempt to help towards #1107, this change simply outputs a number for each hour to show the number of days for which Autotune interpolated a value for the basal rate based on the surrounding hours due to no deviations being classified as basals. This can then be compared to the number of days for which Autotune was run to deduce a "confidence"
> Autotune basal interpolation output

- bin/oref0-autotune-recommends-report.sh
(As reported by Robert Silvers on facebook)
> Fix a typo introduced at d961c841a7fe1d5f2c341b5f10d33dff9497c345.

- lib/determine-basal/determine-basal.js
https://github.com/openaps/oref0/pull/1172/files#r255598505
> Declaration of UAMpredBG breaks determine-basal.js

- lib/determine-basal/determine-basal.js
https://github.com/openaps/oref0/pull/1172/files#r255648093
> Declaration of COBpredBG breaks determine-basal.js

- bin/mm-format-ns-glucose.sh
- bin/mm-format-ns-profile.sh
- bin/mm-format-ns-pump-history.sh
- bin/mm-format-ns-treatments.sh
- bin/mm-format-oref0-glucose.sh
- bin/monitor-xdrip.sh
- bin/nightscout.sh
- bin/ns-dedupe-treatments.sh
- bin/oref0-ns-loop.sh
- bin/oref0-pump-loop.sh
This PR is still a work in progress.
This PR converts most of the calls to the json command to the jq command.  The json command is very resource intensive on the Raspberry Pi Zero. I believe the conversion to the much more effecient jq command will make a noticeable difference in CPU cycles used on the Pi Zero.
> Convert json to jq

- lib/determine-basal/determine-basal.js
Improves the SMB disabled message, as discussed in #853
> Improve SMB disabled message when no criteria are met

- bin/oref0-setup.sh
- Removes pre-compiled binary download options and builds pump communication binaries from source
- Minor changes to setup options to provide more clarity around RFM69HCW radio modules
> Remove binary download options

- bin/oref0-setup.sh
Pass radiotags to oref0-setup.sh from oref0-runagain.sh.
> Radiotags in oref0-runagain.sh

- bin/oref0-setup.sh
Merging mainly to fix the oref0-setup.sh script for this branch involving the pre-compiled Go binaries failing to download and causing the script to terminate early, making the setup difficult.
> Merge dev into offline-xdrip

- bin/oref0-upload-profile.js
This issues a Profile Switch event that AndroidAPS understands and accepts. Docs will follow shortly.
> Allow oref0-upload-profile to also switch to new profile

- bin/oref0-autotune.py
- bin/oref0-autotune.sh
- lib/autotune-prep/categorize.js
* Determine date & dateString properties in prepGlucose map function
* Filter invalid records in filterRecords filter function
* Clean up for loop to remove previously performed checks
* Average any values that fall within the 2 minute deadband
> Categorize improvements for libre 1 minute data

- lib/round-basal.js
- tests/determine-basal.test.js
My first PR. I am interested in eHealth opensource projects. This is my getting the feel of this project :)
This one is really a simple refactoring, while maintaining the functionality.
- ~~no need for own endsWith~~
- parametrized mocha test
> refactoring: round_basal

- lib/autotune-prep/categorize.js
- lib/bolus.js
- lib/meal/total.js
Couple of unused local variables identified by eslint
> Unused local variables

- .travis.yml
- bin/all-autosens-history.sh
- bin/ns-status.js
- bin/openaps-bootstrap.sh
- bin/openaps-install.sh
- bin/openaps-packages.sh
- bin/oref0-autotune.py
- bin/oref0-autotune.sh
- bin/oref0-bluetoothup.sh
- bin/oref0-cron-every-minute.sh
- bin/oref0-cron-nightly.sh
- bin/oref0-get-ns-entries.js
- bin/oref0-mraa-install.sh
- bin/oref0-ns-loop.sh
- bin/oref0-online.sh
- bin/oref0-pump-loop.sh
- bin/oref0-setup.sh
- bin/oref0-upload-profile.js
- lib/autotune-prep/categorize.js
- lib/bolus.js
- lib/determine-basal/determine-basal.js
- lib/meal/total.js
- logrotate.openaps
- package.json
- tests/determine-basal.test.js
* Updates the branch to latest dev 
* Detect socket timeout error for prettier logging
> Update to latest dev & detect socket timeout

- bin/oref0-get-ns-entries.js
* Consolidates router IP reporting to the xDrip load line
* Only log first attempt unless data is available
> Reduced logging

- bin/oref0-online.sh
I want to share the online status with other services (for now with my menu script, but Logger could use ist too).
> Create a status file when public ip found

- bin/oref0-upload-profile.js
(for example: https://site.herokuapp.com/)
> Allow to upload profile even when the url ends with / 

- lib/glucose-get-last.js
- tests/get-last-glucose.test.js
> skip meter bg when getting last glucose

- bin/oref0-pump-loop.sh
Tested by running for 24 hours with and without SMB.
> Remove unused functions.
